### ISSUE TITLE
Not working after last update

### ISSUE THREAD

**Issue by PerryWerneck** [ubuntu/gnome-shell-extension-appindicator#401] opened 2023-02-27 10:27 UTC
After last update only ms-teams icon is showing; all others are missing.

When I enable the extension this show on system log:
`
fev 27 07:24:39 ideapad gnome-shell[16597]: Timelines with detached actors are not supported
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: While initalizing proxy for :1.88@/org/ayatana/NotificationItem/Microsoft_Teams___Preview1: TypeError: method Gio.AsyncInitable.init_async: At least 3 arguments required, but only 2 passed
                                            initAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:120:20
                                            _setupProxy@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:273:31
                                            AppIndicatorsAppIndicator@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:259:14
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:97:31
                                            _ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: While initalizing proxy for :1.591@/org/ayatana/NotificationItem/BBvpn: TypeError: method Gio.AsyncInitable.init_async: At least 3 arguments required, but only 2 passed
                                            initAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:120:20
                                            _setupProxy@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:273:31
                                            AppIndicatorsAppIndicator@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:259:14
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:97:31
                                            _ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: While initalizing proxy for :1.229@/StatusNotifierItem: TypeError: method Gio.AsyncInitable.init_async: At least 3 arguments required, but only 2 passed
                                            initAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:120:20
                                            _setupProxy@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:273:31
                                            AppIndicatorsAppIndicator@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:259:14
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:97:31
                                            _ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad gnome-shell[16597]: JS ERROR: TypeError: this._proxy is undefined
                                            get status@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
                                            get accessibleName@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
                                            _init@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
                                            _registerItem@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
                                            async*_ensureItemRegistered@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
                                            RegisterStatusNotifierItemAsync@/home/perry/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
                                            async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
fev 27 07:24:43 ideapad BBvpn.py[24919]: Unable to connect to the Notification Watcher: GDBus.Error:org.gnome.gjs.JSError.ValueError: this._proxy is undefined
fev 27 07:24:43 ideapad org.telegram.desktop._5adfd0c6540e9ade5cd8d58e044a9a73.desktop[31335]: QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "this._proxy is undefined")
`

**Comment by 3v1n0** [comment] 2023-02-27 15:20
Duplicate of #398

**Closed by 3v1n0** 2023-02-27 15:20 UTC

**Comment by PerryWerneck** [comment] 2023-02-27 19:16
As far I can see #398 seens to be related with an older gnome version isn't? Mine is 41.9.
