### ISSUE TITLE
Some applications dont show since Version 47

### ISSUE THREAD

**Issue by devNan0** [ubuntu/gnome-shell-extension-appindicator#400] opened 2023-02-26 18:57 UTC
Since updating to version 47 the following applications dont show up (but did before):
- mumble
- telegram

```
OS: Debian 11 (buster)
GNOME Shell 3.38.6
```

**Comment by 3v1n0** [comment] 2023-02-27 01:02
Duplicate of #398

**Closed by 3v1n0** 2023-02-27 01:02 UTC
