### ISSUE TITLE
Blank icons after woke up from suspend

### ISSUE THREAD

**Issue by ibahnasy** [ubuntu/gnome-shell-extension-appindicator#329] opened 2022-02-22 13:28 UTC
Every time I wake up the laptop from suspend, there is a new blank icon get inserted in the systray as shown in the screenshot
![Screenshot from 2022-02-22 15-13-43](https://user-images.githubusercontent.com/19417705/155141832-27d45952-dd38-44da-90b1-45c5e995979e.png)
.

**Comment by stefanoginella** [comment] 2022-03-04 08:33
It is happening to me too.

Using Manjaro "Qonos" 21.2.4 with Gnome 41.3 and X11.

**Comment by identithree** [comment] 2022-03-08 16:20
Same here. Every wake from suspend, I get these ghost icons.
I am running Fedora 35 Workstation with GNOME 41.4 with Wayland

**Comment by captfanta** [comment] 2022-03-11 21:50
Same for me using Pop!_OS 21.10 with GNOME 40.4 and X11.

**Comment by camlafit** [comment] 2022-03-14 13:27
it's an #317 duplicate

**Comment by 3v1n0** [comment] 2022-04-14 17:04
Duplicate of #317

**Closed by 3v1n0** 2022-04-14 17:04 UTC
