### ISSUE TITLE
Icons move when locking and unlocking GNOME 3.38 on Debian 11

### ISSUE THREAD

**Issue by malehwi** [ubuntu/gnome-shell-extension-appindicator#306] opened 2021-09-13 08:18 UTC
Hi.

I use Debian 11 with default GNOME 3.38 from its repository. When I lock/unlock GNOME, the icons move to the left. If I ALT+F2 "r" the icons get to the default position. Any fix possible? See the pics attached

![Screenshot from 2021-09-13 09-47-01](https://user-images.githubusercontent.com/78052373/133048600-5a4bdaf1-239b-4e59-8af6-b9c844121eb1.png)

![Screenshot from 2021-09-13 09-47-26](https://user-images.githubusercontent.com/78052373/133048612-d80024f4-5ae7-48b1-b330-93e3a95df6eb.png)

**Comment by 3v1n0** [comment] 2021-09-27 19:10
Do you have other extensions who may add icons to the panel?

**Comment by oxayotl** [comment] 2021-09-27 23:21
Seems very much like a duplicate of this:
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/294
Do you get “empty icons” if you hover on the space between the icons, @malehwi ?

**Comment by hseagle2015** [comment] 2021-10-01 06:13
I have the same problem, but on Debian 11 running GNOME 40.4. Empty icon spaces are appearing when I enable/disable bluetooth. Every time the bluetooth icon appears and disappears from the top tray, empty icon placeholder appears.

Just like @malehwi explained, I'm able to remove empty icon placeholders by restarting gnome-shell.

**Comment by psgreco** [comment] 2021-10-01 10:26
Just to add a bit more information, "empty icons" may appear on both sides of the real icons, and it seems like they only appear when using X11 compat icons, not with native ones (pidgin in my case).

Tested against v41 in fedora 35 beta

**Comment by gersonjferreira** [comment] 2021-12-01 12:49
Same issue here. Running it on Manjaro with Gnome 41.1. On a large monitor this is a small issue, but on my notebook it really gets cumbersome as the icons reach the clock at the middle of the screen and I start loosing access to a couple of them.

Indeed I have too many icons, which must drive Gnome devs crazy! These are: caffeine, Flameshot, Synapse, Insync, MS Teams, Dropox, Slack, and Zulip.

**Comment by ychromosome** [comment] 2022-01-25 14:51
Is there any progress on this bug?

**Comment by gersonjferreira** [comment] 2022-01-25 17:06
it's fixed. I'm running now Gnome 41.3, but I don't know when it was fixed.

**Comment by ychromosome** [comment] 2022-01-25 18:20
I am on Fedora 35 which has Gnome 41.3 and it is still present.
(tested right now)

**Comment by pabs3** [comment] 2022-03-05 11:20
I have the same situation, I found a workaround to delete the empty icons. First do Alt+F2 to bring up the run dialog, then enter 'lg' (without quotes), press Enter, and in the new shell command box use commands like this:

```
Main.panel._centerBox.get_children()[0].destroy()
Main.panel._centerBox.get_children()[2].destroy()
```

The `0` and `2` will vary depending on your setup and your icons, so run the commands without the `.destroy()` first to figure out what each of the children are.

One of the children will be your GNOME clock, you don't want to delete that, but if you do then run this command, lock the screen and unlock and the clock will return.

```
Main.panel.statusArea.dateMenu = new imports.ui.dateMenu.DateMenuButton()
```

**Comment by brianjmurrell** [comment] 2022-03-28 23:19
> it's fixed. I'm running now Gnome 41.3, but I don't know when it was fixed.

No it's not.  I am running 41.3 and it's still happening.

**Comment by 3v1n0** [comment] 2022-04-14 17:32
Duplicate of #317

**Closed by 3v1n0** 2022-04-14 17:32 UTC
