### ISSUE TITLE
GNOME freezes if Discord audio input is on and this extension is also on.

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [ubuntu/gnome-shell-extension-appindicator#157] opened 2019-01-28 23:16 UTC
As weird as it might be, if I use this extension and connect to a discord channel with audio input from a mic it "freezes" the whole desktop.

I say "freezes" with quotes because the mouse still moves, sometimes it changes to other cursors when hovering text for example, but clicking gets locked and it sometimes freezes the system completely.

Disabling this extension removes the issue. How are they connected?

**Comment by st6lls** [comment] 2019-04-24 01:34
i've had this issue since december 2018 and it has been the #1 reason why I don't use GNOME. I would love to be able to use it again if this issue was fixed.

**Comment by 3v1n0** [comment] 2020-02-25 19:42
Duplicate of #171

**Closed** 2020-02-25 19:42 UTC
