### ISSUE TITLE
Tray icon Menu Inconsistency and Double Icons After Locking and Unlocking 

### ISSUE THREAD

**Issue by Raul1198** [ubuntu/gnome-shell-extension-appindicator#423] opened 2023-04-01 07:35 UTC
i have two app with tray icons **telegram** and **motrix** both installed as **Flatpak**, when i run motrix i get this a single white tray menu 
![Screenshot from 2023-04-01 12-42-43](https://user-images.githubusercontent.com/29801315/229272065-86d3b126-f798-49d3-afc7-1c63e407b416.png)
but when i lock and unlock my laptop i get two motrix icon and two different tray menu one with white and other with black menu
![Screenshot from 2023-04-01 12-43-39](https://user-images.githubusercontent.com/29801315/229272109-0f7c476b-0918-4c3f-88a4-c59060c6214b.png)  which is not same as telegram(black menu) here is a video 
[Screencast from 2023-04-01 12-45-06.webm](https://user-images.githubusercontent.com/29801315/229272176-c4b5881f-6de2-4724-966f-eae73559e3e1.webm)

shouldn't motrix have the black menu only istead of white one and only one icon 

here is my distro and list of extension installed 

**Fedora 37 Workstation** - 
![image](https://user-images.githubusercontent.com/29801315/229272308-58967011-2d21-4b08-a89c-6d9c898eccac.png)

**Extension** - 
![image](https://user-images.githubusercontent.com/29801315/229272364-b1813f02-fe3a-4078-9435-a1cae3f47456.png)
 
**Extension Setting** - 
![image](https://user-images.githubusercontent.com/29801315/229272406-ecdbba9c-60f2-4588-8c98-9921ef2c13fa.png)

**Comment by 3v1n0** [comment] 2023-04-01 18:59
Duplicate of #419

**Closed by 3v1n0** 2023-04-01 18:59 UTC
