### ISSUE TITLE
v33 causes intermittent freeze when MEGAsync is running

### ISSUE THREAD

**Issue by Danmou** [ubuntu/gnome-shell-extension-appindicator#226] opened 2020-04-09 17:39 UTC
I'm running Manjaro 19 with GNOME Shell 3.36. After upgrading gnome-shell-extension-appindicator from v32 to v33 I get a full UI freeze regularly every ~10s lasting ~2s. During the freeze no mouse or keyboard input is registered. I found out the problem only occurs when [MEGAsync](https://mega.nz/sync) is running. Any idea why this is happening?

[Corresponding issue with MEGAsync](https://github.com/meganz/MEGAsync/issues/428)

**Comment by danieloppenlander** [comment] 2020-04-27 18:20
I was able to recreate this issue on Ubuntu 20.04 with Gnome 3.36.

I turned off every shell extension until I found that this caused it. I also closed and opened other programs with tray icons until I found that only MEGAsync is the culprit, other tray programs work fine. Furthermore, the issues is solved with Appindicators turned off, but MEGAsync is still running in the background. So somehow it must be a problem with that combo. Did not have this problem in Ubuntu 19.10 with Gnome 3.34.

**Comment by lemome** [comment] 2020-05-01 09:34
I have the exact same problem but with Discord.
I'm on Manjaro, gnome 3.36
On Ubuntu 20.04 the freeze are also present.

**Comment by danieloppenlander** [comment] 2020-05-01 16:38
@Edexiel Interesting, I was not able to recreate the issue with Discord.

**Comment by terencode** [comment] 2020-05-01 16:39
@danieloppenlander To me at least this happens during a call.

**Comment by Edexiel** [comment] 2020-05-01 16:58
@danieloppenlander the freeze is way shorter than @Danmou , a fraction of a second, but also every ~10 seconds
The bug seams to appear , like @terencode said ,only in a call, but maybe after 10-20 minutes of call.
Several people I know that have upgraded to Ubuntu 20.04 also have the bug on different hardware

**Comment by danieloppenlander** [comment] 2020-05-04 18:01
@Edexiel @terencode Does it still happen with appindicators turned off in a Discord call?

**Comment by Edexiel** [comment] 2020-05-04 18:46
@danieloppenlander  No it doesn't happen when the extension is turned off.
I think I found the problem with discord, It seems related to  #171 
![image](https://user-images.githubusercontent.com/3151237/81001440-0754aa00-8e48-11ea-9c16-54f54fec06db.png)
Turning off the reading indicator icon ( and/or ) notifications seems to fix, or lessen the bug, can someone confirm ?

**Comment by danieloppenlander** [comment] 2020-05-04 19:18
@terencode might be the best to confirm.
@Edexiel Do you have the problem with MEGASync too?
Either way it is most likely an issue with appindicators and not only Discord or MEGAsync.

**Comment by Edexiel** [comment] 2020-05-04 19:26
@danieloppenlander I don't use MEGA unfortunately, but my issue seems related to OP

**Comment by danieloppenlander** [comment] 2020-05-04 22:28
@Edexiel You are probably right.

**Comment by terencode** [comment] 2020-05-05 21:56
@danieloppenlander I'll try but what seems to work for me is using push to talk. Can you confirm?

With push to talk, pressing/depressing the button shows this:
```
mai 04 22:52:00 terence-desktop appindicatorsupport@rgcjonas.gmail.com[331812]: discord1, Impossible to lookup icon for 'discord1_565-panel'
mai 04 22:51:59 terence-desktop gnome-shell[331812]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                                     _createIconByName@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:421:26
                                                     _cacheOrCreateIconByName@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:383:14
                                                     _updateIconByType@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:589:18
                                                     _updateIcon@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:622:14
                                                     _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                     _onPropertiesChanged/<@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:221:22
                                                     _onPropertiesChanged@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:215:15
                                                     refreshPropertyOnProxy/<@/home/terence/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
mai 04 22:51:59 terence-desktop appindicatorsupport@rgcjonas.gmail.com[331812]: discord1, Impossible to lookup icon for 'discord1_564-panel'
```

**Comment by danieloppenlander** [comment] 2020-05-05 22:38
@terencode How do I view that log output?

**Comment by Edexiel** [comment] 2020-05-05 23:01
@danieloppenlander journalctl -r should do the trick

**Comment by danieloppenlander** [comment] 2020-05-05 23:46
@terencode I turned on discord push to talk, and `discord_N-panel` and it lists 1 to 660 even when discord is closed or push to talk is off. It does not increment with each press for me.

**Comment by terencode** [comment] 2020-05-06 08:13
@danieloppenlander  Ok, I did not have a chance to test without push to talk but it might just be the same, just the trigger being the voice instead of a button.
I wonder if it starts lagging after reaching this limit of 660...
I might not experience it because it takes longer to go up to 660 with push to talk.

**Comment by IsaacThoman** [comment] 2020-05-08 02:05
I've had the same issue with Pop! OS while in discord calls.

**Comment by kn100** [comment] 2020-05-19 14:01
This issue also affects another app called YTMDesktop. 

### Affected version
PopOS 20.04 LTS with all updates as of now

Gnome Version 3.36.2

Only tested with X11

Nvidia proprietary drivers 440.82

### Bug summary

I have identified a strange interaction between an app called YTMDesktop and Gnome Shell. If YTMDesktop is running and playing or paused, then the entire UI will freeze once per second for a very short period (a few MS). As soon as YTMDesktop is closed, the stuttering stops. I have now identified appindicator as the culprit (see steps to reproduce below).

### Steps to reproduce

1. Install https://ytmdesktop.app/
2. Play anything
3. Open something which is 60fps usually - https://www.testufo.com/framerates#count=1&background=stars&pps=960 is a good test
4. Hopefully observe microstuttering every second
5. Turn off the appindicator extension, and stuttering goes away. Turn it back on, stuttering comes back.

### What happened

Unpleasant stuttering while Ytmdesktop is playing.

### What did you expect to happen

Continue to be lovely and 60fps

### Relevant logs, screenshots, screencasts etc.

I'd love to provide a screencast - but the stuttering is bad enough that the screen recorder doesn't pick up on it - assumedly because it is also stuttering. I realise this bug is somewhat vague, and I am more than happy to provide debug logs/traces/etc if I can be guided to getting them.

**Comment by CorvetteCole** [comment] 2020-05-21 18:11
the fix in #236 works great for me to fix this

**Comment by danieloppenlander** [comment] 2020-05-21 18:44
> the fix in #236 works great for me to fix this

I can't seem to find a fix in that thread.

**Comment by CorvetteCole** [comment] 2020-05-21 21:57
> > the fix in #236 works great for me to fix this
> 
> I can't seem to find a fix in that thread.

ah sorry I meant #237

**Comment by danieloppenlander** [comment] 2020-05-21 22:03
@CorvetteCole Interesting, did you implement it or test it?

**Comment by CorvetteCole** [comment] 2020-05-22 00:59
@danieloppenlander yeah I just changed the file and reloaded the shell and it totally fixes the stuttering for me

**Comment by Mushoz** [comment] 2020-05-26 20:39
Wouldn't it be relatively easy to create a PR with these changes to fix this issue then?

**Comment by danieloppenlander** [comment] 2020-05-27 16:12
I was able to recreate the fix as you described, @CorvetteCole

**Comment by Mushoz** [comment] 2020-05-27 17:30
I can confirm @danieloppenlander's observations. I have applied the fix suggested by @CorvetteCole and there is no more lag for me either.

**Comment by aquaspy** [comment] 2020-05-28 15:40
Is it already live? Thanks!

**Comment by aquaspy** [comment] 2020-05-29 00:26
> I can confirm @danieloppenlander's observations. I have applied the fix suggested by @CorvetteCole and there is no more lag for me either.

Do you know if it is already live? Thanks!

**Comment by danieloppenlander** [comment] 2020-05-29 03:10
@aquaspy I made a PR, but it has not been reviewed yet. Feel free to implement the change yourself for the time being.

**Comment by zeparu** [comment] 2020-06-01 19:09
can confirm the issue too, have been searching the web for a while with "gnome 3.36 stuttering" etc, and even tried to disable non-essential extensions, because i could make out that the gnome-shell process spiked in usage every few seconds, followed by a freeze. problem was that i considered appindicator an essential extension. (for me its because of discord too)

**Comment by CorvetteCole** [comment] 2020-06-08 01:59
this fix does not actually completely solve it in my testing. When apps try to update their icon far too rapidly (e.g. in a voice call in discord) there are still lag spikes etc. I think this extension needs to rate limit icon updates to avoid lag spikes

**Comment by Mushoz** [comment] 2020-06-08 07:06
I can confirm that the issue isn't completely fixed with the earlier mentioned fix unfortunately. Honestly though, I feel like there should be an option to completely disable changing UI icons for now. Gnome extensions do not run in their own thread, so any processing will completely block the main UI thread in the current design. If I have to choose between animated tray icons plus an UI that locks down and static tray icons with a fluent UI then I choose the last option.

Would this be a difficult change/option?

**Comment by kanru** [comment] 2020-06-20 02:33
I did some profiling and it seems that every 10 seconds there is a CPU spike and blocking the UI. Is the tray doing something in this interval?

![Screenshot from 2020-06-20 11-33-02](https://user-images.githubusercontent.com/17571/85189399-d8a46d00-b2e9-11ea-9c95-b4dc75f782af.png)

**Comment by danieloppenlander** [comment] 2020-06-20 04:08
@kanru I get the same thing, I was not able to get as clear a screenshot however. But I recorded one minute with appindicators and the MEGA tray icon turned off (MEGA still running in background, but no icon). The minute with appindicators off, I got no abnormal spikes. The minute with it on I got the exact same regular spikes you are seeing. I cannot find any journalctl output that looks like it could come from it though.

**Comment by kanru** [comment] 2020-06-20 06:41
Perhaps #233 is related. The MEGA is a Qt app.

**Comment by kanru** [comment] 2020-06-20 06:55
Actually the first report has a very good clue. It wasn't so bad in v32. I ran a git bisect between v32 and head, the first bad commit is f0cdd55a530bf2411c37897312eb2f7dbfe362c5

If I revert the commit locally then it no longer freeze intermittently.

Cc @3v1n0

**Comment by skyscooby** [comment] 2020-06-27 01:00
Also seeing this with the Mattermost Desktop Application.. All these reports seem to be Electron based apps? Not sure if that matters.

```
Jun 26 18:57:55 desktop ubuntu-appindicators@ubuntu.com[79778]: Mattermost1, Impossible to lookup icon for 'Mattermost1_717-panel'
Jun 26 18:57:55 desktop gnome-shell[79778]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                                  _createIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:406:26
                                                  _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:368:14
                                                  _updateIconByType@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:574:18
                                                  _updateIcon@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:601:14
                                                  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                  _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:220:22
                                                  _onPropertiesChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:15
                                                  refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:51:19
```

**Comment by danieloppenlander** [comment] 2020-09-17 18:37
@3v1n0 Any idea when this will be released?

**Closed** 2020-09-19 03:52 UTC

**Comment by 3v1n0** [comment] 2020-09-20 14:38
@danieloppenlander v34 is now out, let me know how it works for you

**Comment by zeparu** [comment] 2020-09-20 16:31
i can confirm for myself, that the issue is gone for discord at least, no more freezes in the UI with the new version

*however*, i just re-encountered an old bug for gnome, that previously didnt happen while i manually disabled discord icon updates in the sourcecode

after some time, the font in the gnome shell UI disappears / gets corrupted.
after reading some of the issues with the freezing UI, i manually disabled updates for the discord1 icon in the source code, but now after updating to the new version, and leaving everything as is, the UI font corrupted again, after months of this bug not happening again

im writing this rn after i restarted the shell with alt+f2 "r", but the next time it happens i can post a screenshot

**Comment by danieloppenlander** [comment] 2020-09-20 17:13
> @danieloppenlander v34 is now out, let me know how it works for you

Thanks!

**Comment by danieloppenlander** [comment] 2020-09-21 23:53
@3v1n0 It seems to work so far. I see a massive noticeable performance increase from a direct comparison. I can finally use the system tray!

**Comment by Mirppc** [comment] 2021-01-12 00:20
> i can confirm for myself, that the issue is gone for discord at least, no more freezes in the UI with the new version
> 
> _however_, i just re-encountered an old bug for gnome, that previously didnt happen while i manually disabled discord icon updates in the sourcecode
> 
> after some time, the font in the gnome shell UI disappears / gets corrupted.
> after reading some of the issues with the freezing UI, i manually disabled updates for the discord1 icon in the source code, but now after updating to the new version, and leaving everything as is, the UI font corrupted again, after months of this bug not happening again
> 
> im writing this rn after i restarted the shell with alt+f2 "r", but the next time it happens i can post a screenshot
> 
> edit
> ![image](https://user-images.githubusercontent.com/21054889/93931755-824b2e00-fd1f-11ea-90b2-9ace30c7e56c.png)

Oddly i am having a similar thing pop up in PopOS 20.10 with v34-1
