### ISSUE TITLE
Does not distinguish between left/right click action

### ISSUE THREAD

**Issue by dvorapa** [ubuntu/gnome-shell-extension-appindicator#280] opened 2021-04-25 18:39 UTC
If I left click on tray icon, I expect tray/shell menu to pop up, if I right click, I expect a different action (e.g. VLC should toggle its maximized/minimized state). This works with https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ and https://extensions.gnome.org/extension/1674/topiconsfix/ , but not with this extension apparently. Any mouse button opens me a tray/shell menu

Gnome 40, Xorg

**Comment by 3v1n0** [comment] 2021-04-25 20:59
I'm sorry, but this has never been the design of AppIndicator or StatusNotify.

Some apps *may* support being activated on double-click (mostly Qt ones), but for those using libappindicator, this has always been denied by design (some [old documentation is here](https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators#Design_Guidelines)).

There were various reasons for this, including:
 - Having a consistent behavior with all the apps
 - Make things accessible in any case
 - Discoverability of actions

So, while it may work using legacy tray icon (that did support activation), this is not possible here.

It may be "hacked" for some cases, but really it's not something we want. So I'm closing this.

**Closed by 3v1n0** 2021-04-25 20:59 UTC
