### ISSUE TITLE
Technical details - Archlinux SO

### ISSUE THREAD

**Issue by hidd3nany** [ubuntu/gnome-shell-extension-appindicator#458] opened 2023-08-22 08:51 UTC
The settings of extension appindicatorsupport@rgcjonas.gmail.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by emansom** [comment] 2023-08-22 08:53
Please don't report errors that have nothing to do with this project. A package maintainer on Arch Linux's side fucked up badly, it has nothing to do with this project whatsoever.

**Comment by emansom** [comment] 2023-08-22 08:57
See also #456.

**Comment by 3v1n0** [comment] 2023-08-22 11:54
Duplicate of #456

**Closed by 3v1n0** 2023-08-22 11:54 UTC
