### ISSUE TITLE
Not working after latest update for v47

### ISSUE THREAD

**Issue by dchristofolli** [ubuntu/gnome-shell-extension-appindicator#398] opened 2023-02-24 11:49 UTC
The extension stopped working after latest update for 47. I had to uninstall and manually install the previous version 46, so the extension started working perfectly again.
I'm running gnome shell 3.38.6 in Debian 11 Stable

**Comment by 3v1n0** [comment] 2023-02-24 12:23
I've not tested this in such old versions for some time.

Can you please provide a journal with the failures logs?

Il ven 24 feb 2023, 12:49 Daniel Christofolli ***@***.***> ha
scritto:

**Comment by dchristofolli** [comment] 2023-02-24 14:13
Unfortunately, Debian Stable uses this old version of gnome =/
Is there any way to filter just the issue related logs in journalctl?

**Comment by dagufri** [comment] 2023-02-24 15:10
I got the same problem, and I'm running the same setup.

@dchristofolli Do you happen to have a trick to pin the extension to v46?

**Comment by 3v1n0** [comment] 2023-02-24 15:17
Best way is providing `journalctl /usr/bin/gnome-shell`

Il ven 24 feb 2023, 15:13 Daniel Christofolli ***@***.***> ha
scritto:

**Comment by Doc73** [comment] 2023-02-24 18:49
```
feb 17 14:17:21 debian gnome-shell[1898]: JS ERROR: Gio.DBusError: GDBus.Error:>
                                          _promisify/proto[asyncFunc]/</<@resou>
                                          ### Promise created here: ###
                                          getProxyProperty@/home/myname/.loca>
                                          refreshPropertyOnProxy@/home/myname>
                                          _translateNewSignals/<@/home/myname>
                                          _translateNewSignals@/home/myname/.>
                                          _onProxySignal/<@/home/myname/.loca>
                                          _onProxySignal@/home/myname/.local/>
                                          async*AppIndicatorsAppIndicator/<@/ho>
feb 17 14:17:37 debian gnome-shell[1898]: JS ERROR: Gio.DBusError: GDBus.Error:>
                                          _promisify/proto[asyncFunc]/</<@resou>
                                          ### Promise created here: ###
                                          getProxyProperty@/home/myname/.loca>
                                          refreshPropertyOnProxy@/home/myname>
                                          _translateNewSignals/<@/home/myname>
                                          _translateNewSignals@/home/myname/.>
                                          _onProxySignal/<@/home/myname/.loca>
                                          _onProxySignal@/home/myname/.local/>
                                          async*AppIndicatorsAppIndicator/<@/ho>
feb 17 14:17:42 debian gnome-shell[1898]: JS ERROR: Gio.DBusError: GDBus.Error:>
                                          _promisify/proto[asyncFunc]/</<@resou>
                                          ### Promise created here: ###
```

**Comment by Doc73** [comment] 2023-02-24 18:52
Unfortunately, this extensions upgrades itself on every reboot.
Is there a way to pin it?

**Comment by dchristofolli** [comment] 2023-02-24 19:39
Feb 24 08:14:51 debian gnome-shell[2303]: GNOME Shell started at Fri Feb 24 2023 08:14:48 GMT-0300 (-03)
 373   │ Feb 24 08:14:51 debian gnome-shell[2303]: Registering session with GDM
 374   │ Feb 24 08:14:51 debian gnome-shell[2303]: service string = org.kde.StatusNotifierItem-2733-2
 375   │ Feb 24 08:14:51 debian gnome-shell[2303]: busName string = :1.92
 376   │ Feb 24 08:14:51 debian gnome-shell[2303]: object string = /StatusNotifierItem
 377   │ Feb 24 08:14:52 debian gnome-shell[2303]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object 
       │ /StatusNotifierItem
 378   │                                           _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:435:45
 379   │                                           ### Promise created here: ###
 380   │                                           getProxyProperty@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
 381   │                                           refreshPropertyOnProxy@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
 382   │                                           _translateNewSignals/<@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:268:18
 383   │                                           _translateNewSignals@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:267:50
 384   │                                           _onProxySignal/<@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:56
 385   │                                           _onProxySignal@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:38
 386   │                                           async*AppIndicatorsAppIndicator/<@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:105:76
 387   │ Feb 24 08:14:59 debian gnome-shell[2303]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007
 388   │ Feb 24 08:15:11 debian gnome-shell[2303]: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor2
 389   │ Feb 24 08:15:11 debian gnome-shell[2303]: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor4
 390   │ Feb 24 08:15:11 debian gnome-shell[2303]: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor3
 391   │ Feb 24 08:15:11 debian gnome-shell[2303]: JS ERROR: TypeError: this._proxy is undefined
 392   │                                           get hasNameOwner@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:363:17
 393   │                                           _registerItem/<@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:106:29
 394   │                                           async*_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
 395   │                                           _nameOwnerChanged@/home/daniel/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:14
 396   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
 397   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
 398   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
 399   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
 400   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
 401   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
 402   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
 403   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
 404   │ Feb 24 08:16:01 debian gnome-shell[2303]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
 405   │ -- Boot 1ec4128ebda74551963e1d1e40162db8 --

**Comment by dchristofolli** [comment] 2023-02-24 19:40
@dagufri and @Doc73 I don't know if there is a way to pin the version

**Comment by JOH451** [comment] 2023-02-25 08:34
I temporarily stopped the automatic upgrade to 47 by changing the metadata.json version parameter in 46 to "47". This stops the automatic upgrade until 48 or above comes out. I guess this could be made more permanent by setting it to something like "60" but that would miss a potential fix.

The problem seems to be dependent on indicator. Some work and some don't. For me Mailnag, ClipIT and Indicator Stickynotes seem to work but Dropbox, Owncloud and HP Systray don't. It is not clear whether the problem relates directly to the indicators or at least in some cases their order of loading. I say that because some that fail don't appear to create an error log entry.

06:38:15 dropbox: Unable to connect to the Notification Watcher: GDBus.Error:org.gnome.gjs.JSError.ValueError: this._proxy is undefined
06:38:15 gnome-shell: JS ERROR: TypeError: this._proxy is undefined
get status@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
get accessibleName@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
_init@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
_registerItem@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
async*_ensureItemRegistered@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
RegisterStatusNotifierItemAsync@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34


06:37:22 hp-systray: QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "this._proxy is undefined")
06:37:22 gnome-shell: JS ERROR: TypeError: this._proxy is undefined
get status@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:365:9
get accessibleName@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:373:32
_init@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:232:9
_registerItem@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:117:32
async*_ensureItemRegistered@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
RegisterStatusNotifierItemAsync@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34


06:37:14 gnome-shell: JS ERROR: While initalizing proxy for :1.84@/org/ayatana/NotificationItem/Sticky_Notes: TypeError: method Gio.AsyncInitable.init_async: At least 3 arguments required, but only 2 passed
initAsync@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:120:20
_setupProxy@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:273:31
AppIndicatorsAppIndicator@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:259:14
_registerItem@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:97:31
_ensureItemRegistered@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:142:20
RegisterStatusNotifierItemAsync@/home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:207:24
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

Note that Indicator Stickynotes seems to work even though the above log entry is created.

**Comment by emansom** [comment] 2023-02-25 10:54
Install a previous version system-wide via a debian package, that's the way to pin it.

A alternative route would be upgrading your distro to a newer version, one containing GNOME 40.

**Comment by JOH451** [comment] 2023-02-25 11:26
I don't think installing an old version system-wide will work as a local version takes precedence. What is more an update to a system-wide extension via  GNOME Shell Extension Manager is installed locally. Using a Debian package doesn't alter that functionality.

Upgrading the distro is not an easy option in this case as Debian 11 is the latest stable version.

**Comment by Doc73** [comment] 2023-02-25 11:51
I can't remember why I preferred the upstream version to the repositories version. Maybe the upstream version works better?

[https://packages.debian.org/bullseye/gnome-shell-extension-appindicator](https://packages.debian.org/bullseye/gnome-shell-extension-appindicator)

**Comment by emansom** [comment] 2023-02-25 11:54
> I don't think installing an old version system-wide will work as a local version takes precedence.

Delete the locally user-level installed version.

**Comment by Doc73** [comment] 2023-02-25 19:25
I just tested the version in the Debian Repositories and found that it doesn't work very well.
In my case, it can't load Mega Sync system tray app.

**Comment by 3v1n0** [comment] 2023-02-25 20:10
@dchristofolli the lines numbers in your log does not match the current version, so it's weird.

In any case looks like something calls back on the indicator after we've destroyed it, but I've not yet seen a way to reproduce it locally.

**Comment by 3v1n0** [comment] 2023-02-27 01:05
I've pushed commit 7c1864abdc49f74eaf28f267a0e72918f413b9a4 to master branch, can someone try if that fixes the issue?

It definitely fixes when tested with 3.36, but it could be also something else.

**Comment by devNan0** [comment] 2023-02-27 09:45
Ive tried it and it works for me. Telegram and mumble does show up again.

```
OS: Debian 11 (buster)
GNOME Shell 3.38.6
```

Interestingly this "breaks" the JetBrains Toolbox Indicator, which didn't work with <47 but with 47.
But i don't have a problem with that because the toolbox runs only a few minutes once a week.

**Comment by JOH451** [comment] 2023-02-27 10:40
7c1864a seems to work for me also. Dropbox, Owncloud and HP Systray now show up and operate as normal.

None of the previous error logs are now created including that for Indicator Stickynotes. However the following does appear even though everything seems to work okay.

Feb 27 10:26:57 achilles gnome-shell[2560]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x4800008 specified for 0x4800033.
Feb 27 10:24:12 achilles appindicatorsupport@rgcjonas.gmail.com[2560]: Impossible to send about-to-show to menu: TypeError: this._proxy is null
Feb 27 10:22:40 achilles gnome-shell[2560]: Object St.Icon (0x55baddc2e3c0), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C >
Feb 27 10:22:40 achilles gnome-shell[2560]: #1   7fff394ff800 b   self-hosted:693 (3d81438b9150 @ 15)
Feb 27 10:22:40 achilles gnome-shell[2560]: #0   7fff394ff770 b   /home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:685 (a08ee950880 @ 330)
Feb 27 10:22:40 achilles gnome-shell[2560]: == Stack trace for context 0x55bad9a852e0 ==
Feb 27 10:22:40 achilles gnome-shell[2560]: #1   7fff394ff800 b   self-hosted:693 (3d81438b9150 @ 15)
Feb 27 10:22:40 achilles gnome-shell[2560]: #0   7fff394ff770 b   /home/steve/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:685 (a08ee950880 @ 330)
Feb 27 10:22:40 achilles gnome-shell[2560]: == Stack trace for context 0x55bad9a852e0 ==
Feb 27 10:22:40 achilles gnome-shell[2560]: Object St.Icon (0x55bad9dea880), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C >

This is on Debian 11 and Gnome 3.38.

**Comment by Doc73** [comment] 2023-02-27 14:51
Not working in my case.

`The settings of extension appindicatorsupport@rgcjonas.gmail.com had an error:
```
GLib.FileError: Apertura del file «/home/domenico/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled» non riuscita: open() non riuscita: File o directory non esistente
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:142:31
_init@/home/domenico/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:39:46
buildPrefsWidget@/home/domenico/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:348:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
````

**Comment by 3v1n0** [comment] 2023-02-27 14:53
@Doc73 restarting the shell should fix it, however just do `glib-compile-schemas ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/`

**Comment by Doc73** [comment] 2023-02-27 15:17
@3v1n0 Yes, now it works.

P. S.: it's strange, because in my previous attempt I had restarted the whole pc

**Comment by 3v1n0** [comment] 2023-02-27 15:22
@devNan0 regarding jetbrain toolbox, that's definitely their issue:

```
❯ gdbus call --session --dest com.jetbrains.toolbox --object-path /StatusNotifierItem --method org.freedesktop.DBus.Get org.kde.StausNotifierItem Id
Errore: GDBus.Error:org.freedesktop.dbus.exceptions.DBusExecutionException: Error Executing Method org.freedesktop.DBus.Get: Cannot invoke "Object.getClass()" because "data" is null
```

Now, calling instead `org.freedesktop.DBus.GetAll org.kde.StausNotifierItem` would work, but I'm really not keen on handling buggy clients myself more than needed.

**Comment by 3v1n0** [comment] 2023-02-28 03:29
Closed via https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/7c1864abdc49f74eaf28f267a0e72918f413b9a4

**Closed by 3v1n0** 2023-02-28 03:29 UTC
