### ISSUE TITLE
Major performance impact when using 200% scaling on 4K monitor

### ISSUE THREAD

**Issue by Magean0** [ubuntu/gnome-shell-extension-appindicator#252] opened 2020-10-04 18:56 UTC
Hey,

I've got a very odd issue to report. I've just replaced my old monitor with a 28" 4K one. I set resolution to 3840*2160 with 200% scaling (not just font scaling; full scaling). And then my desktop's performance took a dramatic hit, with regular stutters making even basic web-browsing and emailing a chore, with only a small amount of active windows or tabs. I could even hear abnormal fan noise, signalling that my CPU was struggling. And, indeed, sysprof told me that gnome-shell was responsible for about 90% of CPU load over a couple minutes of everyday tasks, whereas in normal times it's about 5%.

I investigated the matter and unmasked a very unexpected perpetrator: this extension. Indeed, with a naked vanilla GNOME everything is smooth, as it should be. Everything is equally smooth on Windows 10 or KDE by the way, so it's not a hardware problem. I re-enabled extensions one by one and came to the conclusion that my usual batch caused no problem, but for Ubuntu Appindicator. What is more, enabling Appindicator alone (with no other extension on) did cause the issue. Necessary and sufficient condition, one might say...

So, with this single extension on, I plugged my old monitor back (with the new one off) and then Appindicator behaved well. I switched back to the 4K monitor, set the resolution to 3840*2160 and scaling to 100% (so, no scaling) and things remained normally smooth. It's only after I enabled 200% scaling that they went hairy, even after a reboot.

Next, I disabled the version of this extension packaged with Ubuntu 20.04, and replaced it with [the one from the GNOME Extensions website](https://extensions.gnome.org/extension/615/appindicator-support/). Now it works fine, after a reboot and with 200% scaling on.

My system:
Ubuntu 20.04
i7-7700K 4.20 GHz (8 cores)
16 GB Ram
Geforce GTX 1060 6 GB. I normally use proprietary NVidia drivers; the performance issue also manifested with `nouveau` drivers.

For what it's worth, usually the only icon there is in my indicator area is MEGA Sync (a cloud storage service).

Thanks in advance for having a look. I admit this is extremely weird, but at the same time I find it hard to blame anything other than Ubuntu Appindicator considering the tests I've run.

**Comment by physhinx** [comment] 2020-10-19 23:12
Can confirm this issue. I am having the same performance issues caused by this extension (when I disable the extension the performance issues disappear). I only have discord in my tray. 
I am scaling my display by 150% on a 3840*2160 monitor using the built in fractional scaling in ubuntu 20.04. For me, however, the issue is not ameliorated by disabling scaling. When I use 100% scaling I get the same performance issues except the stutters last a bit shorter.

I am using the amdgpu-pro 20.20 drivers on my system:
Ubuntu 20.04
Ryzen 7 3700X (8 cores)
32 GB Ram
Radeon 3700XT (8GB VRAM)

**Comment by 3v1n0** [comment] 2020-10-20 15:18
This issue is known, and addressed in various upstream bug such as #226, however in Ubuntu it's handled as part of http://pad.lv/1884396

That bug is fixed in the development release, but still under [SRU team review](https://wiki.ubuntu.com/StableReleaseUpdates) for 20.04, and waiting in queue. 

I'd suggest to subscribe to that bug to help testing once the version will be in proposed repositories.

Closing this.

**Closed by 3v1n0** 2020-10-20 15:18 UTC
