### ISSUE TITLE
Util.DBusProxy is undefined

### ISSUE THREAD

**Issue by herp1derp2** [ubuntu/gnome-shell-extension-appindicator#466] opened 2023-09-18 13:37 UTC
- Gnome 45.rc 
- Linux 6.5.3-arch1-1
- 
![image](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/145358922/172c47fd-2e1a-4e73-a8e6-ef17a636ca86)

**Comment by AsciiWolf** [comment] 2023-09-18 13:46
This should be fixed in version 57 (that is currently [missing on extensions.gnome.org](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/465)).

**Comment by herp1derp2** [comment] 2023-09-26 17:11
> This should be fixed in version 57 (that is currently [missing on extensions.gnome.org](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/465)).

So when are you going to update it on extensions.gnome.org?

**Comment by snirt** [comment] 2023-10-06 13:31
this error still persist - Gnome 45 on openSUSE Tumbleweed

**Comment by 3v1n0** [comment] 2023-10-09 01:31
Sorry this was already fixed in commit 4bad8037d113bde9a4593db99e5fa7f6a89f2793 but I forgot to upload it to the extensions website.

It's there now.

Duplicate of #457

**Closed by 3v1n0** 2023-10-09 01:31 UTC
