### ISSUE TITLE
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus. Error.Failed: error occurred in AboutToShow

### ISSUE THREAD

**Issue by stuarthayhurst** [ubuntu/gnome-shell-extension-appindicator#445] opened 2023-06-04 18:16 UTC
When opening an indicator icon, I get the following:
```
Jun 04 19:13:36 snakeroot gnome-shell[31862]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.
Error.Failed: error occurred in AboutToShow
                                              _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/
modules/core/overrides/Gio.js:453:45
                                              ### Promise created here: ###
                                              sendAboutToShow@/home/ratus5/.local/share/gnome-shell/exte
nsions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                              sendAboutToShow@/home/ratus5/.local/share/gnome-shell/exte
nsions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:197:22
                                              _onMenuOpened@/home/ratus5/.local/share/gnome-shell/extens
ions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:935:28
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_sign
als.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:1
19:10
                                              open@resource:///org/gnome/shell/ui/popupMenu.js:932:14
                                              toggle@resource:///org/gnome/shell/ui/popupMenu.js:805:18
                                              vfunc_button_press_event@/home/ratus5/.local/share/gnome-s
hell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:425:27
```

So far, I have observed this on Discord, but not psensor.

GNOME: 44.1
Extension version: 53
Distro: Debian Sid (+ Experimental)

Let me know if you need any other information :)

**Comment by nickbp** [comment] 2023-06-06 21:48
Been seeing instability in GNOME with e.g. the whole display freezing up. Suspect it's from upgrading to 44.2.

When checking logs, I noticed the below stacktraces, I'm trying temporarily disabling the extension to see if the issues I'm seeing go away. I don't know if the extension is the cause of the freezes, or if I just happened to notice them because I was looking through the logs.

Samples are from GNOME 44.2, extension 53, Arch linux

```
Jun 07 07:37:14 bling gnome-shell[1516]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         ### Promise created here: ###
                                         sendAboutToShow@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                         sendAboutToShow@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:197:22
                                         attachToMenu@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:864:24
                                         _updateMenu/this._menuReadyId<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:326:38
                                         _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                         _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                         AppIndicatorsClient/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:835:24
                                         _updateLayoutState@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:365:18
                                         _layoutUpdateUpdateAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:346:18
                                         async*_beginLayoutUpdate@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:326:14
                                         _requestLayoutUpdate@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:276:14
                                         initAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:254:14
                                         async*AppIndicatorsClient@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:829:22
                                         _updateMenu@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:318:32
                                         _showIfReady@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:339:14
                                         _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                         _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                         _checkIfReady@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:476:18
                                         checkIfReadyChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:658:50
                                         _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:666:17
                                         _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:662:15
Jun 07 07:37:16 bling gnome-shell[1516]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         ### Promise created here: ###
                                         getProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:553:33
                                         refreshProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:316:48
                                         _refreshOwnProperties/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:202:32
                                         _refreshOwnProperties@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:200:51
                                         _onSignalAsync/refreshPropertiesPromises<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:256:26
                                         _onSignalAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:255:50
                                         async*_onSignal@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:14
                                         _init/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:504:43
Jun 07 07:37:20 bling gnome-shell[1516]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         ### Promise created here: ###
                                         getProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:553:33
                                         refreshProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:316:48
                                         _refreshOwnProperties/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:202:32
                                         _refreshOwnProperties@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:200:51
                                         _onSignalAsync/refreshPropertiesPromises<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:256:26
                                         _onSignalAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:255:50
                                         async*_onSignal@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:14
                                         _init/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:504:43
Jun 07 07:37:44 bling gnome-shell[1516]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         ### Promise created here: ###
                                         sendAboutToShow@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                         sendAboutToShow@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:197:22
                                         _onMenuOpened@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:935:28
                                         _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                         _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                         open@resource:///org/gnome/shell/ui/popupMenu.js:932:14
                                         toggle@resource:///org/gnome/shell/ui/popupMenu.js:805:18
                                         vfunc_button_press_event@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:425:27
Jun 07 07:39:17 bling gnome-shell[1516]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         ### Promise created here: ###
                                         getProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:553:33
                                         refreshProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:316:48
                                         _refreshOwnProperties/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:202:32
                                         _refreshOwnProperties@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:200:51
                                         _onSignalAsync/refreshPropertiesPromises<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:256:26
                                         _onSignalAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:255:50
                                         async*_onSignal@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:14
                                         _init/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:504:43
```

**Comment by crab2313** [comment] 2023-07-09 13:48
Same with dropbox.

**Comment by jrredhorse** [comment] 2023-08-22 16:47
I'm receiving a perhaps identical js error message several times in my system log. 

I'm on an up-to-date version of Fedora f38 Workstation laptop running Gnome 44.3 via Wayland; the Fedora package for gnome-shell-extension-appindicator is marked 53-1.fc38. I have turned off the option "Enable Legacy Tray Icons support".

The application icons that I typically see in my "tray" are from: MullvadVPN, 1Password, and, when I start it manually from the CLI, dropbox.

The main effects I see once completely booted in the the GUI/DE is that one of the icons, MullvadVPN appears as ellipsis dots, 1Password shows as normal, and dropbox as its normal openbox icon. Clicking on the very last icon, dropbox, does not show the underlying menu; the other two show theirs.

Once I lock the screen, then unlock it, all of the tray icons show correctly, and all of the submenus show correctly if I mouse click any of the icons. 

If anyone's out there looking at these, I hope this little bit of added info helps. 
I'm very happy to provide additional information upon request.

Thanks!

**Comment by rxchard** [comment] 2023-09-05 01:10
This is happening on latest Ubuntu mantic for me as well. (gnome-shell 45~beta.1-0ubuntu2, appindicator 57-1)

```
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
### Promise created here: ###
sendAboutToShow@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:501:48
sendAboutToShow@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:198:22
_onMenuOpened@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:932:28
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
open@resource:///org/gnome/shell/ui/popupMenu.js:927:14
_changeMenu@resource:///org/gnome/shell/ui/popupMenu.js:1344:17
_onCapturedEvent@resource:///org/gnome/shell/ui/popupMenu.js:1368:22
@resource:///org/gnome/shell/ui/init.js:21:20
```

I can reproduce this error by opening discord and clicking on the app indicator. (Errors mentioned in https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/445#issuecomment-1579493987 also happen consistently)

Even appears to outright crash the gnome session sometimes.

**Comment by ysolis** [comment] 2023-10-20 03:03
I have the problem, when i am using a theme that change Adwaita (Whitesur-gtk-theme) after this error, Gnome-Shell crashes., if i am in Wayland and i are forced to get logged again but only with X11.

If I maintain the default theme, no crash.

Archilinux, Gnome 45, Ryzen 9

**Comment by ianbmacdonald** [comment] 2023-11-05 03:43
Ubuntu 23.10; 45.0-1ubuntu2;  gnome-shell-extension-appindicator 57-1  I also see this clicking on 1Password, Chrome, Slack  but not all icons, or notably not older ones for less active projects (Solaar, Owncloud) maybe using slightly older methods

**Comment by rmeissn** [comment] 2023-11-13 09:16
I got the same problem on Fedora 39, Gnome 45. Appears in journal right after startup of my system.

**Comment by b3** [comment] 2023-11-17 21:40
Is there a way to stop seeing these (debug) messages in logs under Debian 12.2 (Gnome 43.6, Extension v46-1)?

**Comment by ogarcia** [comment] 2024-01-12 11:15
Still happening with GNOME 45.3 in Arch Linux (extension version 57):
```
ene 12 12:11:05 hell gnome-shell[1767]: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                        
                                        Stack trace:
                                          _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                          @resource:///org/gnome/shell/ui/init.js:21:20
                                          ### Promise created here: ###
                                          sendAboutToShow@file:///home/ogarcia/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                          sendAboutToShow@file:///home/ogarcia/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:198:22
                                          _onMenuOpened@file:///home/ogarcia/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:932:28
                                          _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                          open@resource:///org/gnome/shell/ui/popupMenu.js:937:14
                                          toggle@resource:///org/gnome/shell/ui/popupMenu.js:810:18
                                          _waitForDoubleClick@file:///home/ogarcia/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:377:23
                                          async*vfunc_button_press_event@file:///home/ogarcia/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:415:22
                                          @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by noverd** [comment] 2024-03-03 09:26
also happend for me
```
мар 03 12:24:33 gt-pc2 gnome-shell[1338]: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
                                             
                                             Stack trace:
                                               _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                               @resource:///org/gnome/shell/ui/init.js:21:20
                                               ### Promise created here: ###
                                               getProperty@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusProxy.js:89:33
                                               refreshProperty@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:305:48
                                               _refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:191:32
                                               _refreshOwnProperties@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:189:51
                                               _onSignalAsync/refreshPropertiesPromises<@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:245:26
                                               _onSignalAsync@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:244:50
                                               async*_onSignal@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:203:14
                                               _init/<@file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusProxy.js:40:43
                                               @resource:///org/gnome/shell/ui/init.js:21:20

```

**Comment by becknik** [comment] 2024-03-03 12:33
I'm also facing a similar problem when unlocking my session after locking it. The screen freezes and the GNOME sessions restarts. I'm on NixOS with GNOME 45.4 and gnome-shell-extensions-45.2

This seems to occur more commonly when my system is under load, like compiling multiple packages at once.

The first lines of the system log stacktrace from `journalctl` are looking similar to the ones I read in this thread, so I thought I'd be better to post it here instead of creating a new issue.

<details>

```
Mar 03 13:02:38 dnix .gnome-shell-wr[3047]: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                            
                                            Stack trace:
                                              _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              ### Promise created here: ###
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:198:22
                                              attachToMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:862:24
                                              _updateMenu/this._menuReadyId<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:319:38
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              Client/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:833:24
                                              _updateLayoutState@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:365:18
                                              _layoutUpdateUpdateAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:346:18
                                              async*_beginLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:326:14
                                              _requestLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:276:14
                                              initAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:254:14
                                              async*Client@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:827:22
                                              _updateMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:311:32
                                              _showIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:332:14
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _checkIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:464:18
                                              checkIfReadyChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:646:50
                                              _onPropertiesChanged/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:654:17
                                              _onPropertiesChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:650:15
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              
Mar 03 13:02:38 dnix .gnome-shell-wr[3047]: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                            
                                            Stack trace:
                                              _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              ### Promise created here: ###
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:198:22
                                              attachToMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:862:24
                                              _updateMenu/this._menuReadyId<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:319:38
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              Client/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:833:24
                                              _updateLayoutState@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:365:18
                                              _layoutUpdateUpdateAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:346:18
                                              async*_beginLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:326:14
                                              _requestLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:276:14
                                              initAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:254:14
                                              async*Client@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:827:22
                                              _updateMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:311:32
                                              _showIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:332:14
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _checkIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:464:18
                                              checkIfReadyChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:646:50
                                              _onPropertiesChanged/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:654:17
                                              _onPropertiesChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:650:15
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              
Mar 03 13:02:38 dnix .gnome-shell-wr[3047]: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
                                            
                                            Stack trace:
                                              _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              ### Promise created here: ###
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                              sendAboutToShow@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:198:22
                                              attachToMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:862:24
                                              _updateMenu/this._menuReadyId<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:319:38
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              Client/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:833:24
                                              _updateLayoutState@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:365:18
                                              _layoutUpdateUpdateAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:346:18
                                              async*_beginLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:326:14
                                              _requestLayoutUpdate@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:276:14
                                              initAsync@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:254:14
                                              async*Client@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:827:22
                                              _updateMenu@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:311:32
                                              _showIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:332:14
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _checkIfReady@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:464:18
                                              checkIfReadyChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:646:50
                                              _onPropertiesChanged/<@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:654:17
                                              _onPropertiesChanged@file:///run/current-system/sw/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:650:15
                                              @resource:///org/gnome/shell/ui/init.js:21:20
                                              
Mar 03 13:02:39 dnix org.fcitx.Fcitx5.desktop[709624]: The Wayland connection broke. Did the Wayland compositor die?
Mar 03 13:02:39 dnix Isolated Web Co[4923]: Error reading events from display: Broken pipe
Mar 03 13:02:39 dnix .dolphin-wrappe[3600]: Error reading events from display: Broken pipe
Mar 03 13:02:39 dnix org.fcitx.Fcitx5.desktop[3287]: I2024-03-03 13:02:39.241872 waylandmodule.cpp:248] Connection removed

// more broken pipe messages...

Mar 03 13:02:39 dnix discord.desktop[4548]: XIO:  fatal IO error 13 (Permission denied) on X server ":0"
Mar 03 13:02:39 dnix discord.desktop[4548]:       after 22 requests (22 known processed) with 0 events remaining.
Mar 03 13:02:39 dnix discord.desktop[4548]: Application not signed by Discord, Krisp is not enabled
Mar 03 13:02:39 dnix .io.github.alai[3328]: Error reading events from display: Broken pipe
Mar 03 13:02:39 dnix .evolution-alar[3336]: Error reading events from display: Broken pipe
Mar 03 13:02:39 dnix pipewire[3555]: mod.x11-bell: X11 I/O error handler called on display :0
Mar 03 13:02:39 dnix pipewire[3555]: mod.x11-bell: X11 display (:0) has encountered a fatal I/O error
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.Shell@wayland.service: Main process exited, code=killed, status=9/KILL
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.SettingsDaemon.Color.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.SettingsDaemon.Keyboard.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.SettingsDaemon.MediaKeys.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.SettingsDaemon.Wacom.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: plasma-dolphin.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: plasma-dolphin.service: Failed with result 'exit-code'.
Mar 03 13:02:39 dnix systemd[2700]: xdg-desktop-portal-gnome.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: xdg-desktop-portal-gnome.service: Failed with result 'exit-code'.
Mar 03 13:02:39 dnix systemd[2700]: org.gnome.SettingsDaemon.XSettings.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:02:39 dnix systemd[2700]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE

// more "status=1/FAILURE" and "Failed with result 'exit-code'." messages...

Mar 03 13:02:39 dnix dbus-daemon[2711]: [session uid=1000 pid=2711] Monitoring connection :1.117 closed.
Mar 03 13:02:39 dnix systemd[1]: Started Process Core Dump (PID 709658/UID 0).
Mar 03 13:02:39 dnix systemd[1]: Started Process Core Dump (PID 709674/UID 0).
```

Eventually, the GNOME session restarts

</details>

**Comment by sergio-costas** [comment] 2024-03-04 20:30
This is due to an incorrect implementation of the appindicator API in other apps. In my case it happens with mattermost. These applications do send DBus calls to change their icon, but don't implement the "other side" of the API, specifically the `AboutToShow` method, which is called by appindicator when the user clicks on the icon and the menu is "about to be shown".

**Comment by 3v1n0** [comment] 2024-04-18 19:41
Closing this as per #525. Note that this has never been a problem or a crash, just a log message with extended stack trace.

**Closed by 3v1n0** 2024-04-18 19:41 UTC

**Comment by noverd** [comment] 2024-04-19 05:21
Ok.
