### ISSUE TITLE
indicators shift left with screen unlock

### ISSUE THREAD

**Issue by 6itH** [ubuntu/gnome-shell-extension-appindicator#317] opened 2021-11-20 06:44 UTC
Hi, I noticed this shifting of all the indicators to the left, by exactly one (indicator) space, every time I unlock my screen. This seems to happen if I have Teams running (I suspect its indicator is causing the issue). I noticed this on three different machines. Nothing needs to be done to reproduce the issue, it just happens. Here are the details:
- Ubuntu 21.10 freshly installed (nothing really changed to the original version)
- Teams last version installed from Microsoft
- At every screen lock/unlock all the indicators (Teams + others if any, not the system ones) have been shifted to the left, leaving on their right exactly one empty (indicator) space. An empty circle (indicator) can be seen if the mouse is hovered over this empty space
- With every additional screen lock/unlock the indicators are shifted to the left by an additional empty space
- The same effect can be reproduced if turning on/off the Ubuntu Appindicators extension in the Extensions app. Every time is turned off and back on again, another empty space is added to the right of the indicators
- To reset this and have the indicators aligned back to the right a logout or restart is needed

**Comment by 6itH** [comment] 2021-11-20 06:55
![Screenshot from 2021-11-20 06-54-23](https://user-images.githubusercontent.com/94733250/142717671-cff526be-b70d-425c-a543-cc7c8bab8096.png)

**Comment by 6itH** [comment] 2021-11-20 10:15
Update: the snap version of Teams doesn't seem to be affected.

**Comment by taraszka** [comment] 2021-11-20 11:44
@6itH just tested, I am running on Arch. Both: snap version and non-snap version of teams - same behavior

**Comment by 6itH** [comment] 2021-11-20 12:45
> @6itH just tested, I am running on Arch. Both: snap version and non-snap version of teams - same behavior 

Thanks for testing. When you say same behaviour you mean they are affected or unaffected by this issue? I haven't tried on Arch, but I didn't see this happening on previous versions of Ubuntu

**Comment by taraszka** [comment] 2021-11-20 12:49
> > @6itH just tested, I am running on Arch. Both: snap version and non-snap version of teams - same behavior
> 
> Thanks for testing. When you say same behaviour you mean they are affected or unaffected by this issue? I haven't tried on Arch, but I didn't see this happening on previous versions of Ubuntu

oh, sorry, I wasn't clear enough - both versions are affected by this bug.

**Comment by VS-X** [comment] 2021-11-25 09:35
Same here with Fedora 35:  
![Screenshot from 2021-11-25 11-33-40](https://user-images.githubusercontent.com/8009182/143416393-b6c9c1b4-6f85-4ad6-b1a5-472cd4717885.png)

**Comment by taraszka** [comment] 2021-11-27 15:24
I think it is working fine if you are at Wayland, not X11. At least I've switched to Wayland - and this issue is gone.

**Comment by VS-X** [comment] 2021-11-29 09:24
I'm on Wayland already. I did not try switching to X11 though.

**Comment by 6itH** [comment] 2021-11-29 10:04
On Ubuntu 21.10 both Wayland and X11 are affected

**Comment by not-a-kiwi** [comment] 2021-12-15 00:26
Same issue on Fedora 35, Gnome 41.2, Wayland. Currently with those icons: nm-applet (I need it for wireguard support, looking at you NetworkManager-gnome), Telegram and dnssec-trigger-panel.
Same thing, locking/unlocking or turning the extensions off/on will make the space used by the extension grow with the latter much more "reliable". Interestingly when off there are still plenty of phantom indicators, visible by hovering with the mouse.

**Comment by ixevix** [comment] 2021-12-19 08:18
This has nothing to do with Teams. I have discord, virt-manager and barrier running and it still happens.

**Comment by ixevix** [comment] 2021-12-19 08:18
It also seems to repro just by disabling and enabling the extension.

**Comment by ixevix** [comment] 2021-12-19 08:19
looks like a duplicate https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/306

**Comment by cliy5602** [comment] 2022-01-28 09:38
Same issue icons shifting left
![image](https://user-images.githubusercontent.com/43173294/151522796-853591db-2497-481a-8037-bfe5339a2d78.png)
OS info
![image](https://user-images.githubusercontent.com/43173294/151522841-aa5f5228-8111-4e58-a3ce-299f3323b69a.png)

Wayland for me did not raise this issue. But I cannot use Wayland since it does not allow MS teams app to share the screen. So I had to switch to X11 to mitigate that issue, then this happened.

Really looking forward to a solution or workaround.

**Comment by WilsontheWolf** [comment] 2022-01-29 23:36
I have the same issue on Arch Linux, Gnome 41.3, wayland, gnome-shell-extension-appindicator 41-1. Don't have microsoft teams.

**Comment by NathanaelA** [comment] 2022-02-05 23:59
I would merge this issue (#317) & #306 into #294.  They all appear to be the same issue.

**Comment by mauromarinoni** [comment] 2022-02-28 06:54
Same behavior (empty/null icons) on Debian Testing, Wayland, Gnome 42.beta, gnome-shell-extension-appindicator 42.

**Comment by pabs3** [comment] 2022-03-05 11:19
I have the same situation, I found a workaround to delete the empty icons. First do Alt+F2 to bring up the run dialog, then enter 'lg' (without quotes), press Enter, and in the new shell command box use commands like this:

```
Main.panel._centerBox.get_children()[0].destroy()
Main.panel._centerBox.get_children()[2].destroy()
```

The `0` and `2` will vary depending on your setup and your icons, so run the commands without the `.destroy()` first to figure out what each of the children are.

One of the children will be your GNOME clock, you don't want to delete that, but if you do then run this command, lock the screen and unlock and the clock will return.

```
Main.panel.statusArea.dateMenu = new imports.ui.dateMenu.DateMenuButton()
```

**Comment by pabs3** [comment] 2022-03-05 11:20
I have the same situation, I found a workaround to delete the empty icons. First do Alt+F2 to bring up the run dialog, then enter 'lg' (without quotes), press Enter, and in the new shell command box use commands like this:

```
Main.panel._centerBox.get_children()[0].destroy()
Main.panel._centerBox.get_children()[2].destroy()
```

The `0` and `2` will vary depending on your setup and your icons, so run the commands without the `.destroy()` first to figure out what each of the children are.

One of the children will be your GNOME clock, you don't want to delete that, but if you do then run this command, lock the screen and unlock and the clock will return.

```
Main.panel.statusArea.dateMenu = new imports.ui.dateMenu.DateMenuButton()
```

**Comment by ixevix** [comment] 2022-03-05 12:35
you can alternatively just Alt+F2 and 'r' and it will reload the gnome shell.

**Comment by pabs3** [comment] 2022-03-05 12:36
That doesn't work with GNOME Wayland yet unfortunately.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by WilsontheWolf** [comment] 2022-03-05 15:13
Actually someone posted somewhere else this. 
Alt + f2 and `lg` than run 
```js
let boxes = [
     ...imports.ui.main.panel._rightBox.get_children(),
     ...imports.ui.main.panel._leftBox.get_children(),
     ...imports.ui.main.panel._centerBox.get_children()
 ];
 for (var v of boxes) {
     let fc = v.first_child?.first_child?.first_child;
     if (fc && fc.window === null) { v.destroy(); }
 };
```
This will remove all the blank spaces while keeping everything else intact.

**Comment by mauromarinoni** [comment] 2022-03-08 09:09
@WilsontheWolf solution works like a charm. 

There is a simple way to put it in a script to corn it?

**Comment by WilsontheWolf** [comment] 2022-03-08 15:46
@mauromarinoni I'm not sure if there is. Both the alt + f2 and console windows do have command history thought so you can just push the up arrow until it pops back up.

**Comment by okennedy** [comment] 2022-03-14 20:39
A quicker reproduction is to go into Gnome Extensions and turn Ubuntu Appindicators off and then back on.  It will leave behind an empty tray icon each time this is done.

As another workaround, I've (temporarily) disabled Appindicators and installed https://extensions.gnome.org/extension/615/appindicator-support/ in its place.

**Comment by pabs3** [comment] 2022-03-15 02:04
The "AppIndicator and KStatusNotifierItem Support" extension links back
to this repo, so presumably it is the same extension repackaged? Is it
an old version of the same extension? Perhaps there is a commit that we
can revert to get the old behaviour back?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by Picklejar05** [comment] 2022-03-15 02:19
this repo also links to that extension in the readme, so I believe that it is the same thing. Also I have the issue and originally installed from https://extensions.gnome.org/extension/615/appindicator-support/ so I have no idea how that fixed it for you

**Comment by brianjmurrell** [comment] 2022-03-28 23:17
> A quicker reproduction is to go into Gnome Extensions and turn Ubuntu Appindicators off and then back on. It will leave behind an empty tray icon each time this is done.

I can reproduce this doing exactly this also.
 
> As another workaround, I've (temporarily) disabled Appindicators and installed https://extensions.gnome.org/extension/615/appindicator-support/ in its place.

Which is this extension, isn't it?

**Comment by brianjmurrell** [comment] 2022-03-28 23:22
This bug seems to have been reported in a number of issues here.

Is there any hope of it being fixed?  It's rather annoying as it starts to push your extensions all into one-another.

**Comment by 3v1n0** [comment] 2022-04-19 12:37
Can you see if this commit fixes it?

https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/b62ac8d2451e27fb01bef12657ac10710c3a65cf

You can also just use the [ubuntu/jammy branch](https://github.com/ubuntu/gnome-shell-extension-appindicator/commits/ubuntu/jammy)

**Comment by 3v1n0** [comment] 2022-04-19 12:39
Duplicate of #294

**Closed by 3v1n0** 2022-04-19 12:39 UTC
