### ISSUE TITLE
Icons vertically stretched on HIDPI display

### ISSUE THREAD

**Issue by valmar** [Ubuntu/gnome-shell-extension-appindicator#110] opened 2017-11-15 15:57 UTC
On my HIDPI display (I have a Dell XPS 13 with 3200x1800 resolutions), icons are blurry and vertically stretched. I am using 200% scaling.

![screenshot from 2017-11-15 16-46-32](https://user-images.githubusercontent.com/558469/32845655-9110c89e-ca25-11e7-91e4-f6f188a2585b.png)

Apart from this problem, the icons are perfectly functional

Please let me know if you need more information and thanks for developing this great extension

**Comment by jhasse** [comment] 2017-11-15 18:35
What Linux distro are you using? Which version of the extension are you using?

**Comment by valmar** [comment] 2017-11-15 18:41
Thank you for looking into this. I am using Fedora 27 but I experienced the
same in Ubuntu 17.10 Beta

I am using the version from extensions.gnome.org

**Comment by jhasse** [comment] 2017-11-15 18:54
Do you know Git and could check if an older version improves this?

Unfortunately I don't have a HiDPI display to test.

**Comment by valmar** [comment] 2017-11-15 18:55
I do! Which commit should I try? (I will try tomorrow)

On Nov 15, 2017 7:54 PM, "Jan Niklas Hasse" <notifications@github.com>
wrote:

Do you know Git and could check if an older version improves this?

Unfortunately I don't have a HiDPI display to test.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/110#issuecomment-344691822>,
or mute the thread

**Comment by jhasse** [comment] 2017-11-15 19:03
https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/e2de1b7e6d82868de37404b65883315c8efcbb5c
and
https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/28d0ac87dd449250e56f9e5fae6c0d61492a877f
for now. Thanks in advance!

**Comment by valmar** [comment] 2017-11-16 17:25
@jhasse I run some tests. Here are the results

Git head, master branch: no difference

Git e2de1b7: the icons changed order when I restarted the shell, but otherwise they are still stretched

Git 28d0ac8: The icons are smaller, but still stretched. See image

![screenshot from 2017-11-16 18-24-16](https://user-images.githubusercontent.com/558469/32905823-6671c814-cafb-11e7-829c-dd66899bb5bd.png)

I will be traveling until the next tueday, but then I am available for more tests!

Thank you again

**Comment by fonorobert** [comment] 2017-11-17 20:41
i am seeing nearly the same issue, icons are not blurry for me but are stretched just like for @valmar.
would be happy to help test @jhasse 
gnome 3.26.2 on Manjaro linux, latest version of the extension from extensions.gnome.org, same display on the XPS13

**Comment by fonorobert** [comment] 2017-11-17 20:48
installed it from AUR (latest git version), i see the same thing

**Comment by jhasse** [comment] 2017-11-24 08:59
If possible, could you try if this also happens with GNOME 3.24 or earlier?

**Comment by valmar** [comment] 2017-11-24 09:16
Uhm, I cannot without reinstalling unfortunately.....

**Comment by jhasse** [comment] 2017-11-24 10:02
No worries, I'll try to set up a virtual machine with 200% scaling to see if I can reproduce the issue.

**Comment by echonaut** [comment] 2017-12-07 19:05
So you'll have to forgive me as I've never really understood how GIT works, but I believe I've found the problem. 

In commit 1c839c3f82cb5086371f76b9aebbb09e2defb0d3 there was a scale_factor added:

`+        this._iconSize      = icon_size * scale_factor

By removing the scale_factor it fixes the problem.

**Comment by jhasse** [comment] 2017-12-08 09:38
Just the `* scale_factor` in that line or reverting the whole commit?

**Comment by echonaut** [comment] 2017-12-08 13:48
@jhasse I’m not much of a coder so it’s hard for me to say what reverting the whole commit would do. I ONLY removed the ‘* scale_factor’ to fix it on my machine. I’m sure all the stuff that calculates that could have been removed too since I removed the variable (unless it’s used somewhere else)

**Comment by simonvanderveldt** [comment] 2018-01-28 11:33
> Just the * scale_factor in that line or reverting the whole commit?

Just removing `* scale_factor` from this line makes it better, though for example the Slack icon is still 32 
 pixels high instead of the 22px height of the native GNOME icons.

**Comment by kicsyromy** [comment] 2018-01-30 17:37
@simonvanderveldt Can you test with my PR to see if it fixes the issue for you? I'm also using 200% scaling and the icons look OK for me now.

**Comment by heroheman** [comment] 2018-02-07 13:21
tried the changes, app icons are looking normal now. thanks @kicsyromy
Tested on 17.10 (on xorg), xps15 with 4k display.

**Comment by kicsyromy** [comment] 2018-02-07 19:17
@heroheman Glad to hear, now if I could just get some feedback from the maintainers to know if this could be pushed upstream 😄

**Comment by fonorobert** [comment] 2018-02-16 08:29
@jhasse maybe? ☝️

**Comment by jhasse** [comment] 2018-02-16 08:37
See #113

**Comment by fonorobert** [comment] 2018-02-16 08:40
Ahh, sorry, missed that

**Comment by jhasse** [comment] 2018-03-03 15:53
Okay I've merged the patch as it really makes sense for the people who are using this extension from Git. For the update on e.g.o 3v1n0 has to do it.

**Closed by jhasse** 2018-03-03 15:53 UTC
Labels: bug

**Comment by valmar** [comment] 2018-05-07 09:26
@3v1n0 has this been released somehow? Is there something I can do to help this going into the official release?

**Comment by amezin** [comment] 2018-08-20 18:12
@3v1n0 Could you update the extension on extensions.gnome.org, please?

**Comment by PHLAK** [comment] 2018-10-09 19:02
+1 @amezin's comment, let's get this updated on extensions.gnome.org

**Comment by goetas** [comment] 2018-11-04 18:19
is it planned a new v23 release? I have this issue too.

**Comment by simonvanderveldt** [comment] 2018-11-07 09:10
> @simonvanderveldt Can you test with my PR to see if it fixes the issue for you?
> I'm also using 200% scaling and the icons look OK for me now.

@kicsyromy Just tried current master and it's not correct for me. While the icon isn't stretched anymore as it used to be it's too large now. See 
![image](https://user-images.githubusercontent.com/204286/48121448-49ae2280-e275-11e8-8422-fb09ad12eb4e.png)

I'm using 2880x1800 at 200% scaling.

**Comment by adelavega** [comment] 2018-11-14 02:28
Having the same issue here on a Dell XPS 15 on Ubuntu 18.10

**Comment by Saroumane** [comment] 2018-12-12 02:04
Same issue here, useful information is scattered, so let's gather it : 

```
sudo apt-get remove gnome-shell-extension-appindicator
git clone https://github.com/ubuntu/gnome-shell-extension-appindicator
cd gnome-shell-extension-appindicator
ln -s $PWD ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com
gnome-shell-extension-tool -e appindicatorsupport@rgcjonas.gmail.com
```
Alt + F2, then "r" to restart gnome.

**Comment by PHLAK** [comment] 2018-12-12 15:55
This is greate @Saroumane but wouldn't it be better to clone the extension directly into the gnome-shell extensions folder?

    sudo apt-get remove gnome-shell-extension-appindicator
    git clone https://github.com/ubuntu/gnome-shell-extension-appindicator ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com
    gnome-shell-extension-tool -e appindicatorsupport@rgcjonas.gmail.com

**Comment by Saroumane** [comment] 2018-12-12 22:37
Maybe it could get overwritten later ?
Frankly I don't know. 
(Personally I have a dedicated folder in my $HOME for local compilation and other code manually recovered by git)

**Comment by StrangeNoises** [comment] 2018-12-12 23:22
I just tried this out, as per @Saroumane's instructions a few comments up, on Ubuntu 18.10 everything-up-to-date. It does seem to fix the stretched icons, but as others have reported, they're *all* now a bit too big.

I want to add, before doing this (thus on the current ubuntu version of the package on 18.10), not *all* the icons were stretched. So, the three I use commonly are Nextcloud-client (current version 2.5.1), Enpass 6.0 beta, Slack (from flatpak, as the deb version segfaults). The nextcloud-client version showed up the correct size *and* the correct aspect ratio, so in other words, completely correctly. Both the others were stretched vertically to fill the height of the panel.

Now they're all the correct aspect ratio, but now too big overall. It's almost like the fix was to stretch them horizontally by the same excessive amount that they were already being stretched vertically, rather than to not stretch them vertically by too much in the first place. As a result, as I look at the double-sized screenshots pasted below, I can see they're all more fuzzy around the edges.

Why just one application worked correctly before, I have no idea.

(It's still an improvement this way. The vertically stretched ones are really distracting. These, not so much.)

before - ubuntu cosmic gnome-shell-extension-appindicator 22-1:

![screenshot from 2018-12-12 23-13-03](https://user-images.githubusercontent.com/1295001/49904943-d1ceab80-fe63-11e8-896e-c8e44f3f981a.png)

after - git describe: v17-46-g7bd97d4:

![screenshot from 2018-12-12 23-14-33](https://user-images.githubusercontent.com/1295001/49904952-ddba6d80-fe63-11e8-85c6-0fa0fec7e3db.png)


This is all with a desktop scaling factor of 200%.

**Comment by jmvrbanac** [comment] 2019-03-18 03:55
FYI: As of writing this, trunk isn't compatible with 18.10. I had to do a `git checkout 7bd97d4ca7cfc487cf73530bb70a17c028dfc2e8` prior to enabling the extension.

**Comment by kkga** [comment] 2019-03-20 17:26
Using the latest version and still seeing the same issue: icons are stretched on a HiDPI screen.

**Comment by imfromthenet** [comment] 2019-07-22 11:36
Still having issues on Ubuntu 18.10.

**Comment by foobnix** [comment] 2020-05-20 13:33
Still having an issue on Ubuntu 20.04 (200% scale) with some apps (Default apps shows well)
![Screenshot from 2020-05-20 16-33-20](https://user-images.githubusercontent.com/432440/82452208-a53aac80-9ab7-11ea-9cf0-a9b30d6aed7c.png)

![Screenshot from 2020-05-20 16-32-41](https://user-images.githubusercontent.com/432440/82452138-8dfbbf00-9ab7-11ea-97d0-1a8433f12ea5.png)

**Comment by kicsyromy** [comment] 2020-07-11 05:41
> Still having an issue on Ubuntu 20.04 (200% scale) with some apps (Default apps shows well)
> ![Screenshot from 2020-05-20 16-33-20](https://user-images.githubusercontent.com/432440/82452208-a53aac80-9ab7-11ea-9cf0-a9b30d6aed7c.png)
> 
> ![Screenshot from 2020-05-20 16-32-41](https://user-images.githubusercontent.com/432440/82452138-8dfbbf00-9ab7-11ea-97d0-1a8433f12ea5.png)

@foobnix I don't think this is related, the issue is only for StatusNotifier items on the right side of the top panel, not the Application menu on the right
