### ISSUE TITLE
High CPU usage when used together with Qt app

### ISSUE THREAD

**Issue by SamSchott** [ubuntu/gnome-shell-extension-appindicator#233] opened 2020-04-27 17:37 UTC
QSystemTrayIcon has the bad habit of sending both the icon name and pixmap over Dbus, even if the icon exists in the platform theme. This is typically not a problem, unless you enable HiDPI support in Qt. It then decides for some reason to send 512x512 px icons over Dbus.

In Ubuntu 19.10, this wasn't a problem. However, in Ubuntu 20.04, the GUI slows to crawl and becomes almost unusable when updating the tray icon. Has there been any change in how pixmaps are processed when a valid icon name is provided?

Gnome shell: 3.36
Extension version: probably v33? the default that comes with Ubuntu 20.04

**Comment by 3v1n0** [comment] 2020-09-19 03:33
This is should be now a bit improved, unfortunately we can't prevent the pixmap to be read, when there's no other option.

Duplicate of #226

**Closed by 3v1n0** 2020-09-19 03:33 UTC
