### ISSUE TITLE
Regression: Jammy to Noble, right clicking on some icons shows dropdown on left side of screen

### ISSUE THREAD

**Issue by theofficialgman** [ubuntu/gnome-shell-extension-appindicator#515] opened 2024-03-30 01:15 UTC
In ubuntu jammy and previous releases, right clicking on appindicator icons brings up the menu below the appindicator with appropriate gnome theming. In ubuntu noble, right clicking on some appindicator icons (example: barrier) results in the menu appearing on the left side of the screen without proper theming.

![2024-03-29_21-09](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/28281419/0d64e85f-94a0-4df4-9897-60cfad4fa5ea)

https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/2059819

**Comment by 3v1n0** [comment] 2024-04-18 19:44
Likely a duplicate of #516 at least in its manifestation, can you confirm?

**Comment by theofficialgman** [comment] 2024-04-18 22:03
I checked, implementing [#516](https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/519/files) does nothing to fix this issue.

One thing I will note is on Jammy the barrier menu can be opened with a single left click. A single left click on Noble does nothing at all for barrier. A right click pops the menu up on the left like shown above.

**Comment by 3v1n0** [comment] 2024-04-18 22:04
What you see is the legacy menu that an indicator may show when double-clicked, once that would help.

**Comment by 3v1n0** [comment] 2024-04-24 18:28
I've tested this in noble with barrier but I couldn't reproduce, can you please provide more steps?

**Comment by 3v1n0** [comment] 2024-04-25 15:32
So, I've checked this again and indeed you're right in fact it's enough to run the shell in an X11 session with this hack:

```diff
diff --git a/statusNotifierWatcher.js b/statusNotifierWatcher.js
index 915c860..8fa50c8 100644
--- a/statusNotifierWatcher.js
+++ b/statusNotifierWatcher.js
@@ -23,6 +23,7 @@ import * as Interfaces from './interfaces.js';
 import * as PromiseUtils from './promiseUtils.js';
 import * as Util from './util.js';
 import * as DBusMenu from './dbusMenu.js';
+import * as ShellUtil from 'resource:///org/gnome/shell/misc/util.js';
 
 import {DBusProxy} from './dbusProxy.js';
 
@@ -41,6 +42,15 @@ const DEFAULT_ITEM_OBJECT_PATH = '/StatusNotifierItem';
 export class StatusNotifierWatcher {
     constructor(watchDog) {
         this._watchDog = watchDog;
+        this._initAsync().catch(logError);
+    }
+
+    async _initAsync() {
+        ShellUtil.spawn(['barrier']); // or clementine or any Qt app
+        await new PromiseUtils.TimeoutSecondsPromise(
+            2, GLib.PRIORITY_DEFAULT, null);
+        print('wait done');
+
         this._dbusImpl = Gio.DBusExportedObject.wrapJSObject(Interfaces.StatusNotifierWatcher, this);
         try {
             this._dbusImpl.export(Gio.DBus.session, WATCHER_OBJECT);
```

HOWEVER... This is not an extension bug but rather a Qt issue, in fact:
 - [They don't](https://github.com/qt/qtbase/blob/6.7.1/src/gui/platform/unix/dbusmenu/qdbusmenuconnection.cpp) check for [`IsStatusNotifierHostRegistered`](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierWatcher/) property value (and changes) (this partially [happened](https://github.com/qt/qtbase/commit/447f3ade9a284d52552352e2752c53be2cf0a57e) before a change by @ilya-fedin)
 - [They don't](https://github.com/qt/qtbase/blob/6.7.1/src/gui/platform/unix/dbusmenu/qdbusmenuconnection.cpp) check for `StatusNotifierHostRegistered` signal emission to update the state of the dbus menu availability
 - [They don't](https://github.com/qt/qtbase/blob/6.7.1/src/gui/platform/unix/qgenericunixthemes.cpp) update the state of the dbus tray support availiability (and the current icons mode) based on that.

So, really nothing we can do at extension level. So I'd rather suggest you to report a bug to Qt.

Also, the position of the menu is something that we don't control in the extension, a part passing to the shell the event when the user clicked, so we can't really do anything at this level, but I've proposed [a fix upstream](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3283).

**Closed by 3v1n0** 2024-04-25 15:32 UTC

**Comment by ilya-fedin** [comment] 2024-04-25 15:40
> * [They don't](https://github.com/qt/qtbase/blob/6.7.1/src/gui/platform/unix/dbusmenu/qdbusmenuconnection.cpp) check for [`IsStatusNotifierHostRegistered`](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierWatcher/) property value (and changes) (this partially [happened](https://github.com/qt/qtbase/commit/447f3ade9a284d52552352e2752c53be2cf0a57e) before a change by @ilya-fedin)

It's not necessary to listen for its changes if it's not queried at all - checking for watcher changes should be enough. In other words, my changes made the chance of the legacy API usage lesser, in case the watcher is registered while the host is not yet: before the change it would fallback to legacy tray icon in such case but now will use SNI anyway.

The root problem is it doesn't listen for watcher changes, which I reported long time ago as https://bugreports.qt.io/browse/QTBUG-94871. Personally i don't really believe they will fix it, it looks to me like a big refactoring of abstractions is needed for that to happen (would really like to be proven wrong!)...

**Comment by 3v1n0** [comment] 2024-04-29 15:23
Thanks for the info, in any case, the fdo API says that having a watcher doesn't mean that we've an host, while the host availability is what should make apps to consider that they can use the appindicator.

**Comment by ilya-fedin** [comment] 2024-06-03 07:30
I added some more quick improvements so in 6.5.7/6.7.2/6.8.0 it should automatically update dbus availability on Wayland at least. On X11, applications will be able to manually update the used backend by recreating QSystemTrayIcon object, e.g.:
```
// assuming m_trayWatcher is a std::optional<QDBusServiceWatcher>
m_trayWatcher.emplace("org.kde.StatusNotifierWatcher", QDBusConnection::sessionBus());
connect(&*m_trayWatcher, &QDBusServiceWatcher::serviceOwnerChanged, this, [=](const QString &serviceName, const QString &oldOwner, const QString &newOwner) {
    // assuming m_trayIcon is a std::optional<QSystemTrayIcon>
    m_trayIcon.emplace();
    m_trayIcon->setIcon(...);
    m_trayIcon->setTooltip(...);
    m_trayIcon->setContextMenu(...);
    m_trayIcon->show();
});
```
