### ISSUE TITLE
Slack is not supported

### ISSUE THREAD

**Issue by antonpaisov** [ubuntu/gnome-shell-extension-appindicator#86] opened 2017-09-17 22:28 UTC
Slack indicator stays in the traditional Gnome place. Confirmed that I'm not the only one who get's it http://www.omgubuntu.co.uk/2017/03/use-indicator-applets-gnome-shell#comment-3209346101

If this somehow matters - topicons extension supports slack indicator.

**Comment by jhasse** [comment] 2017-09-18 07:14
Thanks for reporting :) I think Slack uses Electron, which has a workaround for this bug (https://github.com/electron/electron/commit/dc43dc2a1316d5f96e1c3a9cf6079c4150214f66), but we'll need for Slack to update to a newer Electron version for this to work. A real fix is discussed here: https://github.com/electron/electron/issues/10427

Duplicate of #74.

**Closed by jhasse** 2017-09-18 07:14 UTC
