### ISSUE TITLE
Wine support

### ISSUE THREAD

**Issue by MartinPL** [ubuntu/gnome-shell-extension-appindicator#222] opened 2020-03-31 18:08 UTC
I would be nice to have wine support.

Current wine implementation tray look like this: 
![xd](https://i.imgur.com/U4ipiRC.png)

**Comment by jhasse** [comment] 2020-04-02 15:24
This needs to be fixed in WINE, see https://bugs.winehq.org/show_bug.cgi?id=38409

**Closed by jhasse** 2020-04-02 15:24 UTC

**Comment by Espionage724** [comment] 2023-08-14 23:54
I'm running Jagex Launcher through Wine ([notes](https://wiki.realmofespionage.xyz/games:wine:old_school_runescape_jagex_launcher_c)); it does a separate Wine System Tray without `gnome-shell-extension-appindicator`, but with that installed it puts the launcher icon in the indicator bar.

The problem is that the launcher when its in the indicator bar can't be interacted with. Left and right-clicks don't do anything.

Left and right-click works fine most of the time when it's in the Wine System Tray (left-click sometimes causes the main Jagex Launcher window to appear and disappear but I think that's unrelated to the tray support).

**Comment by psklb** [comment] 2023-09-05 16:00
same problem here. With [sticky](https://www.zhornsoftware.co.uk/stickies/) program (old version 8) under wine. Really nice app for stickies between local LAN users. 
Pb is that right-clic (only way to write a new sticky) is not available when icon is in systray. Work when icon is in ugly systray window like first post. 

manjaro / gnome-shell 44.4  appindicator 53

Notice that right clic had worked in a previous configuration (gnome-shell / extention app indicator) but can remember whose. an if I try to install a previous version of extension, it is update immediately. 

As a basic user, I can't get further. Hope someone could find a solution
