### ISSUE TITLE
Electron apps don't seem to work in Fedora 28

### ISSUE THREAD

**Issue by aia832003** [ubuntu/gnome-shell-extension-appindicator#141] opened 2018-07-31 02:31 UTC
So far the only app that shows an indicator for me is the Insync Google Drive app. Mailspring, Transmission, and Slack all show nothing. Is there an added package to make this work inside a non-Ubuntu based distro? I can confirm that the same apps present an icon on Ubuntu 18.04 and Pop OS.

**Comment by treba123** [comment] 2018-09-06 23:32
This is a bug in electron: https://github.com/electron/electron/issues/10427
There is a workaround: https://github.com/electron/electron/issues/10427#issuecomment-386024975
For fedora, you'd probably have to add `fedora:GNOME` to that list (haven't tested yet).

But well, it's a quite sad state atm :(

**Comment by Jeansen** [comment] 2018-09-29 21:36
@treba123 Oh, I see. Well, thank you for the background details :smile:

**Comment by jhasse** [comment] 2020-04-02 15:38
As this really needs to be fixed in Electron / Chromium I will close this issue.

btw: It seems that Electron 8 has changed something in this regard. I can confirm that Electron apps display a tray icon in Fedora 31, not sure if it's due to those changes.

**Closed by jhasse** 2020-04-02 15:38 UTC
