### ISSUE TITLE
3 icons replaced by dots

### ISSUE THREAD

**Issue by patricklibert** [ubuntu/gnome-shell-extension-appindicator#411] opened 2023-03-07 16:44 UTC
Ubuntu 22.04

The latest update today totally screwed things up.

Deluge, ULauncher and RadioTray trayicons are replaced with 3 dots icons.

See picture in attachment

![kstatus](https://user-images.githubusercontent.com/647670/223489965-e814ddf1-9bff-4a2b-bd6f-4d4fac25de74.png)

**Comment by 3v1n0** [comment] 2023-03-08 01:42
Please provide a log, however a `git bisect` could help to figure out the guilty commit.

**Comment by 3v1n0** [comment] 2023-03-08 18:52
Duplicate of #410

**Closed by 3v1n0** 2023-03-08 18:52 UTC
