### ISSUE TITLE
Error after updating from GNOME Shell Extensions Website

### ISSUE THREAD

**Issue by keelbeelveel** [ubuntu/gnome-shell-extension-appindicator#333] opened 2022-02-28 16:12 UTC
Hi, I'm not super familiar with GNOME shell extensions but after updating to the latest version today, the on/off slider is replaced with ERROR. Uninstalling and reinstalling does not fix this.
![image](https://user-images.githubusercontent.com/57582123/156017532-05ea8b61-40d3-433a-b5c5-49841958706c.png)

I am on Debian 11. Thank you. If nothing else, how can I revert to the older version? As I said I am unfamiliar with shell extensions.

**Comment by alysa-mad** [comment] 2022-03-01 05:23
I'm suffering from the same problem :(
![image](https://user-images.githubusercontent.com/85077374/156109994-3718d6eb-e3b1-469a-bf83-e6935fba4e52.png)

**Comment by 3v1n0** [comment] 2022-03-01 08:15
Duplicate of #332

**Closed by 3v1n0** 2022-03-01 08:15 UTC
