### ISSUE TITLE
Nextcloud icon missing in gnome 3.34

### ISSUE THREAD

**Issue by uncles-a-m** [ubuntu/gnome-shell-extension-appindicator#190] opened 2019-09-29 09:24 UTC
After updating to Gnome 3.34 on Arch, the Nexcloud icon is missing. Update to the newest version of the extension didn't solve the issue.

**Comment by epsilontheta** [comment] 2019-10-04 17:16
For me `libappindicator-gtk3` was missing.
After installing it everything worked as expected.

**Comment by uncles-a-m** [comment] 2019-10-05 08:44
Thanks for your comment, epsilontheta. 
`libappindicator-gtk3 ` is installed on my system but the nextcloud icon is missing nevertheless.

**Comment by unholyeyebrows** [comment] 2019-10-06 05:57
Hi, I have the same issue with Ubuntu 19.10 Eoan Beta.

**Comment by epsilontheta** [comment] 2019-10-06 17:57
I think it is a timing related problem. When logging in and having nextcloud in autostart there is no icon. When stopping nextcloud, e.g. with ´killall nextcloud`, and manually starting it the icon appears. Can you reproduce this?

**Comment by unholyeyebrows** [comment] 2019-10-06 18:11
Hi - this doesn't help on Ubuntu Eoan i.e regardless of whether the client is started automatically or manually I never get the icon.

**Comment by uncles-a-m** [comment] 2019-10-07 04:47
epsilontheta, I can reproduce this behaviour. When I kill nextcloud and start it manually afterwards, the icon is shown as expected.

**Comment by kas7yler** [comment] 2019-10-10 03:33
Same with copyq & goldendict. No icon if auto-started, but launching manually works.

**Comment by jhasse** [comment] 2020-04-02 15:31
I think this is a duplicate of #98. Feel free to reopen.

**Closed by jhasse** 2020-04-02 15:31 UTC

**Comment by marbx** [comment] 2022-10-16 11:44
I have just set up Debian 11 with Gnome 3.38.5 on a new laptop.

The NextCloud systray icon is missing, which is strange because I use the same setup as for my current laptop.

After exiting NextCloud and starting again the systray icon appears.

NextCloud is started by a *.desktop file.

The *.desktop file seems to have no "delayed start" option
https://specifications.freedesktop.org/desktop-entry-spec/latest/


I therefore use `sleep 2` with this workaround
```
$ grep Exec  .config/autostart/com.nextcloud.desktopclient.nextcloud.desktop 
Exec=/usr/bin/nextcloudSleep.sh

$ cat /usr/bin/nextcloudSleep.sh 
sleep 2 
/usr/bin/nextcloud --background
```

With this workaround, the systray icon appears after a delay of 2 seconds after login.


The `.config/autostart/com.nextcloud.desktopclient.nextcloud.desktop` file will probably be overwritten with the next NextCloud update.
