### ISSUE TITLE
Log flooded with error messages

### ISSUE THREAD

**Issue by gergof** [ubuntu/gnome-shell-extension-appindicator#520] opened 2024-04-11 08:27 UTC
Hi! I really love your extension and it's making my life so much easier. Recently the extension started to produce a ton of error logs which started to flood my drive (about 5GB in ~24 hours). The message is always the same and is logged about 1-2 times per second:

```
Apr 11 11:23:40 glap2 gnome-shell[3257]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
                                         ### Promise created here: ###
                                         getProperty@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:553:33
                                         refreshProperty@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:316:48
                                         _refreshOwnProperties/<@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:202:32
                                         _refreshOwnProperties@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:200:51
                                         _onSignalAsync/refreshPropertiesPromises<@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:256:26
                                         _onSignalAsync@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:255:50
                                         async*_onSignal@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:14
                                         _init/<@/home/gergo/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:504:43
```

**Comment by 3v1n0** [comment] 2024-04-18 20:37
There are applications that don't properly implement the specification and so we may get errors, however they should not block the extension to work.

**Comment by 3v1n0** [comment] 2024-04-18 20:39
Duplicate of #511

**Closed by 3v1n0** 2024-04-18 20:39 UTC
