### ISSUE TITLE
Discord spams system.log with ubuntu_appindicator error

### ISSUE THREAD

**Issue by angry-frog** [ubuntu/gnome-shell-extension-appindicator#241] opened 2020-05-27 06:32 UTC
Gnome shell 3.36 Ubuntu 20.04 (same error on Ubuntu 18.04)
appindicator version "latest from extensions.gnome.org"

ERROR:
Constant spamming to system.log while talking on discord app installed through snap (sudo snap install discord) 
ERROR MESSAGE: (output of System.log (over 2000 of these errors in past day)
-----------------------------------------------------------------------------------------------------------
discord1, Impossible to lookup icon for 'discord1_12-panel'
JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
_createIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:406:26
_cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:368:14
_updateIconByType@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:574:18
_updateIcon@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:601:14
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_onPropertiesChanged/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:220:22
_onPropertiesChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:15
refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:51:19
---------------------------------------------------------------------------
DUPLICATION OF ERROR:
Start discord and join a voice chat.
in terminal run $journalctl /usr/bin/gnome-shell -f -o cat
as you speak you will see the errors pile up.

If you turn off the appindicator extention the errors will stop

NOTE: Not sure if this is an issue with Discord or Appindicator, or if discord is not properly using the extension.  Some research online has shown that this error is not new.  

My assumption is that Discord is trying to get the icon/indicator to flash or indicate that you are talking.  

Thank you for reading this.  Hope a solution can be found.

**Comment by Dragon8oy** [comment] 2020-06-05 18:47
This is also causing periodic freezes for the whole shell, making it very frustrating to use.

**Comment by robobenklein** [comment] 2020-06-08 06:41
@Dragon8oy I confirmed the stutter bug a long time ago: https://trello.com/c/T9S0mSLm

**Comment by Dragon8oy** [comment] 2020-06-08 09:13
> @Dragon8oy I confirmed the stutter bug a long time ago: https://trello.com/c/T9S0mSLm

I know, but it wasn't mentioned on this thread

**Comment by Gonm1** [comment] 2020-08-11 19:58
This bug still exists and is still causing the whole shell to freeze every some seconds

**Comment by 3v1n0** [comment] 2020-09-19 03:24
Duplicate of #236

**Closed** 2020-09-19 03:25 UTC
