### ISSUE TITLE
After update to Gnome 43, app indicator shows ellipsis instead of icon

### ISSUE THREAD

**Issue by dhanak** [ubuntu/gnome-shell-extension-appindicator#450] opened 2023-07-13 17:30 UTC
I have just upgraded to Debian 12, and thus to Gnome 43. I have three applications which display an app icon: keepassxc, mega and dropbox. The latter two still display their icons properly, but the icon for keepassxc is unexpectedly replaced by an ellipsis.

![image](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/55064/c3ad09e4-0825-422b-8c7e-85b44ed9fb3d)

For a brief period, the dropbox icon was also replaced with an ellipsis, but that "fixed itself" after some clicking.

Do you have any idea why this happens? Without the icon, status indication is also missing.

**Comment by janvlug** [comment] 2023-07-20 08:14
This is probably a duplicate of https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/283.

**Comment by BobUzer** [comment] 2023-08-07 20:06
I have the same issue happening. For me it is my vpn app icon appearing as an ellipsis. If I lock my screen and then unlock it, the proper vpn icon then displays. My issue is not related to Flatpaks as some have reported in other issues.

If I click on the ellipsis, the normal and expected vpn options appear.
This issue is new for me, on a recent Fedora install. I have also tested in in VM's with Gnome on Debian 12 and the issue also happens there.

Fedora 38
Gnome 44.3
Wayland

**Comment by 3v1n0** [comment] 2023-08-17 00:48
Duplicate of #283

**Closed by 3v1n0** 2023-08-17 00:48 UTC
