### ISSUE TITLE
Log spam: `org.kde.StatusNotifierItem.IconAccessibleDesc` missing?

### ISSUE THREAD

**Issue by hunger** [ubuntu/gnome-shell-extension-appindicator#380] opened 2022-11-10 09:32 UTC
I get two or three of these messages in `journalctl --user` per second while this extension is active:

```
Nov 10 10:26:05 computer gnome-shell[1809]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object /org/kde/statusnotifieritem/6_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
    ### Promise created here: ###
    getProxyProperty@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
    refreshPropertyOnProxy@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
    _translateNewSignals/<@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:268:18
    _translateNewSignals@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:267:50
    _onProxySignal/<@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:56
     _onProxySignal@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:38
     async*AppIndicatorsAppIndicator/<@/home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:105:76
```

This is using version 46 of the extension on gnome 43.

Any idea how I can quieten this down a bit?

**Comment by DomiStyle** [comment] 2022-11-18 12:04
Same issue here on Fedora 37 with Gnome 43 (happened in 42 as well).

The cause of it for me is the Nextcloud Flatpak: https://flathub.org/apps/details/com.nextcloud.desktopclient.nextcloud

```
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object /StatusNotifierItem
                                           _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
                                           ### Promise created here: ###
                                           getProxyProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
                                           refreshPropertyOnProxy@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
                                           _translateNewSignals/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:265:18
                                           _translateNewSignals@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:264:50
                                           _onProxySignal/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:291:56
                                           _onProxySignal@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:291:38
                                           async*AppIndicatorsAppIndicator/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:102:76
```

**Comment by ttys3** [comment] 2022-11-21 02:03
I got this too.

```
 gnome-shell[2271]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Unknown interface org.kde.StatusNotifierItem or property IconAccessibleDesc.
                                        _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
                                        ### Promise created here: ###
                                        getProxyProperty@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
                                        refreshPropertyOnProxy@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
                                        _translateNewSignals/<@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:268:18
                                        _translateNewSignals@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:267:50
                                        _onProxySignal/<@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:56
                                        _onProxySignal@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:38
                                        async*AppIndicatorsAppIndicator/<@/home/ttys3/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:105:76
```

**Comment by rmader** [comment] 2022-11-26 12:17
I see this as well on Fedora 37 with Gnome 43 with the Nextcloud indicator.

**Comment by darkblaze69** [comment] 2022-12-16 18:06
Have this issue with telegram installed.

**Comment by darkblaze69** [comment] 2022-12-17 16:17
Seems duplicate of this issue #370 which is fixed.
Just upgrade to latest master version, and spamming is gone.

**Closed** 2023-03-03 01:39 UTC
