### ISSUE TITLE
extension creates invisible indicators when turned off and then on

### ISSUE THREAD

**Issue by BaigHack3rss** [ubuntu/gnome-shell-extension-appindicator#359] opened 2022-08-25 21:33 UTC
Hello there,
I wanted to report this bug. Whenever I have more than 1 application open and I lock and then unlock my gnome session, there is a new empty app-indicator box. The empty box only goes away after gnome-shell is restarted. I have attached 2 screenshots of both scenarios.
I am running gnome with mutter-rounded on arch linux. 
![Screenshot from 2022-08-25 17-28-21](https://user-images.githubusercontent.com/77700401/186772362-facd4b73-4242-4fb0-912a-8ac4219fc797.png)

![Screenshot from 2022-08-25 17-32-39](https://user-images.githubusercontent.com/77700401/186772834-a6fae009-7fbb-4f58-a2e3-e1d6f127fd4e.png)

**Comment by yjzzjy4** [comment] 2022-08-26 01:04
I can confirm this bug. Multiple locks and unlocks leads to something like below:

![image](https://user-images.githubusercontent.com/43295657/186793675-bdf28ebd-e1ba-4955-8369-3b4029e3528d.png)

The huge gap contains invisible app icons, and in my case, those icons seems all to be the first app in the visible tray (which is vmware's tray icon under the circumstance).

I'm running Ubuntu 20.04.5 with GNOME Shell 3.36.9.

**Comment by yvoitenko** [comment] 2022-08-29 17:05
Same here, especially after the screen lock and unlock. GNOME 42.3.1, Manjaro Stable

**Comment by jeton-th** [comment] 2022-09-14 11:42
> Same here, especially after the screen lock and unlock. GNOME 42.3.1, Manjaro Stable

Same case for me. Arch Linux, GNOME 42.4.

**Comment by BentHaase** [comment] 2022-09-14 18:15
Same here, looks horrible and can only be fixed by reloading the shell (when running on Xorg). Fedora 36, GNOME Shell 42.4

**Comment by resiehnnes** [comment] 2022-09-18 14:28
Same issue, running Fedora 36, GNOME Shell 42.4, X11

**Comment by static302** [comment] 2022-09-22 09:45
Same problem, Fedora 36, Gnome Shell 42.4, Wayland

**Comment by 3v1n0** [comment] 2022-09-25 23:10
Duplicate of #294

**Closed by 3v1n0** 2022-09-25 23:10 UTC
