### ISSUE TITLE
Shell 46 Beta error occurred in AboutToShow

### ISSUE THREAD

**Issue by jbicha** [ubuntu/gnome-shell-extension-appindicator#502] opened 2024-02-19 13:41 UTC
- gnome-shell 46 Beta
- Ubuntu 24.04 LTS
- gnome-shell-extension-appindicator 57-2 (with 5c6400d7922771eef1894ee9aba967c4ce994c87 )

My systemd journal shows the below error. The extension seems to work though.

This guide was recently published:

https://gjs.guide/extensions/upgrading/gnome-shell-46.html

```
Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow

Stack trace:
  _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
  @resource:///org/gnome/shell/ui/init.js:21:20
  ### Promise created here: ###
  sendAboutToShow@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:501:48
  sendAboutToShow@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:198:22
  attachToMenu@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:862:24
  _updateMenu/this._menuReadyId<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:319:38
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  Client/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:833:24
  _updateLayoutState@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:365:18
  _layoutUpdateUpdateAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:346:18
  async*_beginLayoutUpdate@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:326:14
  _requestLayoutUpdate@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:276:14
  initAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:254:14
  async*Client@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:827:22
  _updateMenu@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:311:32
  _showIfReady@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:332:14
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  _checkIfReady@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:464:18
  checkIfReadyChanged@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:646:50
  _onPropertiesChanged/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:654:17
  _onPropertiesChanged@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:650:15
  @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by rmeissn** [comment] 2024-02-28 10:18
I'm on Gnome-Shell 45.4, extension version 57, Fedora 39 and observed the following error in my journal:
```
Feb 28 11:04:56 framework gnome-shell[3031]: Gio.IOErrorEnum: Zeitüberschreitung wurde erreicht
                                             
                                             Stack trace:
                                               asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
                                               @resource:///org/gnome/shell/ui/init.js:21:20
                                               
Feb 28 11:04:56 framework gnome-shell[3031]: Gio.IOErrorEnum: Zeitüberschreitung wurde erreicht
                                             
                                             Stack trace:
                                               _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                               @resource:///org/gnome/shell/ui/init.js:21:20
                                               ### Promise created here: ###
                                               sendAboutToShow@file:///home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
                                               sendAboutToShow@file:///home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:198:22
                                               _onMenuOpened@file:///home/user/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:932:28
                                               _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                               _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                               open@resource:///org/gnome/shell/ui/popupMenu.js:937:14
                                               _changeMenu@resource:///org/gnome/shell/ui/popupMenu.js:1361:17
                                               _onCapturedEvent@resource:///org/gnome/shell/ui/popupMenu.js:1385:22
                                               @resource:///org/gnome/shell/ui/init.js:21:20
                                               
Feb 28 11:04:56 framework gnome-shell[3031]: Gio.IOErrorEnum: Zeitüberschreitung wurde erreicht
                                             
                                             Stack trace:
                                               asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
                                               @resource:///org/gnome/shell/ui/init.js:21:20

```

**Comment by sergio-costas** [comment] 2024-02-29 17:30
@jbicha I have this same error, and I tracked it to mattermost. It seems that it doesn't implement the answer for AboutToShow...

**Comment by sergio-costas** [comment] 2024-02-29 17:46
@jbicha I have this same error, and I tracked it to mattermost. It seems that it doesn't implement the answer for AboutToShow... Specifically, it is sending that call to the object /com/canonical/dbusmenu with the interface com.canonical.dbusmenu. Clicking on the mattermost's appindicator to show the menu triggers this. It looks more like a bug in the mattermost client.

About the other error, it is also (in my case) from mattermost. The extension tries to get the object properties by calling the Get method from the /StatusNotifierItem object, interface org.freedesktop.DBus.Properties, but it fails for some reason...

**Comment by sergio-costas** [comment] 2024-02-29 18:33
Also, I found a bug in gjs overrides: the DBus promise doesn't trigger an exception, it just shows the error message in the journal but resolves the promise. I'll fix this tomorrow.

**Comment by sergio-costas** [comment] 2024-03-01 12:49
My fault: the DBus promise does trigger an exception; the problem is that it returns a generic DBus error, so we can't detect this specific case. I think that the only way of fixing this is to send a patch for mattermost.

Anyway, I think that a good idea is to add some extra debugging info (the called method and the destination DBus address, object and method) to allow to better detect the culprit in these cases. I'll prepare a patch for that.

**Comment by sergio-costas** [comment] 2024-03-01 12:58
Probably not. If the mattermost code is the same, the bug is also in flatpak. It's not really a problem, because the calls are just "informative" (they are used to notify the app that the menu has been shown).

**Comment by ngnpope** [comment] 2024-03-04 19:38
Looks like a duplicate of #434 and #445? _(I'm seeing this on gnome-shell v45.4 with v57 of the extension.)_

**Closed** 2024-04-18 19:37 UTC

**Comment by 3v1n0** [comment] 2024-04-18 19:40
Closing this as per #525. Note that this has never been a problem or a crash, just a log message with extended stack trace.
